Fixing the path
faros-ai/airbyte-connectors pull request #101
Opened 2021-09-27 20:47 UTC by tovbinm

## Description

> Provide description here

## Type of change
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change

2021-09-27 22:00 UTC, tovbinm commented
@Roma-Kyrnis I am fixing it right now in this PR - https://github.com/faros-ai/airbyte-connectors/pull/101

2021-09-27 23:44 UTC, cjwooo requested changes

2021-09-27 23:44 UTC, cjwooo commented on .github/workflows/ci.yml
> +          PHABRICATOR_SOURCE_TEST_CREDS: ${{ secrets.PHABRICATOR_SOURCE_TEST_CREDS }}
These and the corresponding Github secrets need to be renamed to `..._CONFIG`.

2021-09-28 01:51 UTC, cjwooo commented on .github/workflows/ci.yml
> +          PHABRICATOR_SOURCE_TEST_CREDS: ${{ secrets.PHABRICATOR_SOURCE_TEST_CREDS }}
Actually these should just be removed.

2021-09-28 02:03 UTC, cjwooo commented on .github/workflows/ci.yml
> +          PHABRICATOR_SOURCE_TEST_CREDS: ${{ secrets.PHABRICATOR_SOURCE_TEST_CREDS }}
I've updated the CI workflow.

2021-09-28 02:14 UTC, cjwooo approved these changes

2021-09-28 03:22 UTC, merged