[FAI-6768] Add destination packaging test to ci.yml
faros-ai/airbyte-connectors pull request #1064
Opened 2023-06-26 18:22 UTC by JoshSauter

## Description
Issues like the one which happened when we bumped Commander package which [had to be reverted](https://github.com/faros-ai/airbyte-connectors/pull/1063) might be able to be caught before merging by attempting the destination packaging within our CI workflow

2023-06-26 18:29 UTC, tovbinm commented on .github/workflows/ci.yml
> +          cd destinations/airbyte-faros-destination && \
I think `cd destinations/airbyte-faros-destination && npm i` should be enough

2023-06-26 22:15 UTC, tovbinm approved these changes

2023-06-26 22:34 UTC, tovbinm requested changes
hmm, sec...

2023-06-26 22:55 UTC, tovbinm commented
I think we should create a new job and invoke it on PRs only.

2023-06-26 23:05 UTC, tovbinm reviewed
@JoshSauter @cjwooo please have a look

2023-06-26 23:05 UTC, tovbinm approved these changes

2023-06-27 14:48 UTC, JoshSauter reviewed
LGTM assuming my comment is accurate (can't approve since it's technically my PR)

2023-06-27 14:48 UTC, JoshSauter commented on .github/workflows/ci.yml
> +          cd faros-airbyte-common && \
I assume each of these steps starts from the base directory and not from the previous step?

2023-06-27 14:48 UTC, JoshSauter commented
The new step is failing with:
`npm ERR! notarget No matching version found for faros-airbyte-cdk@0.0.1.`

2023-06-27 18:11 UTC, tovbinm commented on .github/workflows/ci.yml
> +          cd faros-airbyte-common && \
yes

2023-06-27 18:47 UTC, merged