FAI-8579 - Added Files Source with S3 support
faros-ai/airbyte-connectors pull request #1248
Opened 2023-12-04 16:19 UTC by dbruno21

## Description

- Added Files Source which can be used to read files. 
- Currently it supports reading JSON files from S3 given a path on a bucket, but could be extended to reading from other sources as well as supporting other file formats.
- Incremental sync support.
- Pagination handling when listing S3 objects

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2023-12-05 17:49 UTC, tovbinm requested changes

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/cfg.json
the file is empty. remove it?

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/resources/schemas/files.json
> +  "properties": {
any additional fields we should add? created at, modified at, size etc

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/resources/spec.json
> +        "description": "Only S3 supported",
```suggestion
```

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/resources/spec.json
> +                "description": "AWS Session Token",
`AWS Session Token` should be optional. AWS key id + secret should be enough.

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/resources/spec.json
> +        "title": "Stream Name",
why do we need this?

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/src/files-reader.ts
> +        }
this should not be a mandatory argument. aws key + secret should be enough,.

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/resources/spec.json
> +              },
please specify in description which AWS IAM perms are required

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/src/files-reader.ts
> +        }
We should not try parse into json. instead read the contents into string and yield it. We will handle the parsing in Faros Destination

is it base64 encoded or?

2023-12-05 17:49 UTC, tovbinm commented on sources/files-source/resources/spec.json
> +        "description": "Only S3 supported",
let's also add a `Local` file mode. this would be useful for testing.

2023-12-06 14:21 UTC, ypc-faros commented on sources/files-source/resources/spec.json
> +        "title": "Stream Name",
Same as other "generic" sources (e.g., sheets, aws-cloudwatch-metrics) we use this to make sure the appropriate converter is used on the destination

2023-12-06 16:26 UTC, tovbinm commented on sources/files-source/src/files-reader.ts
> +        if (lastModified && object.LastModified.getTime() <= lastModified)
Is there a way to avoid client side filtering?

2023-12-11 14:32 UTC, ypc-faros commented on sources/files-source/src/files-reader.ts
> +        }
`aws_session_token` is optional

2023-12-11 15:23 UTC, dbruno21 commented on sources/files-source/resources/schemas/files.json
> +  "properties": {
not needed for now

2023-12-11 16:57 UTC, tovbinm commented on sources/files-source/src/files-reader.ts
> +          type: 'S3',
`fileSource: 'S3'`

2023-12-14 17:10 UTC, tovbinm commented on sources/files-source/resources/schemas/files.json
> +    "content": {
let's change to `contents`

2023-12-14 17:11 UTC, tovbinm approved these changes

2023-12-14 17:13 UTC, tovbinm requested changes
see comments

2023-12-14 17:25 UTC, dbruno21 commented on sources/files-source/resources/schemas/files.json
> +    "content": {
done

2023-12-14 17:25 UTC, dbruno21 commented on sources/files-source/src/files-reader.ts
> +        const content = await res.Body.transformToString();
done

2023-12-14 17:47 UTC, tovbinm approved these changes

2023-12-14 17:47 UTC, merged