FAI-9231 | Partial Vuln Fix - curl CVE-2023-38545
faros-ai/airbyte-connectors pull request #1304
Opened 2024-01-24 19:14 UTC by omreego

## Description

https://nvd.nist.gov/vuln/detail/CVE-2023-38545

## Type of change
- [X] Bug fix
- [ ] New feature
- [ ] Breaking change

2024-01-24 20:34 UTC, tovbinm commented on Dockerfile
> +FROM node:21-alpine
before we do this, we need to update the node version across the whole repo and make sure it compiles & runs - for example https://github.com/faros-ai/airbyte-connectors/pull/542

2024-01-24 20:34 UTC, tovbinm requested changes
not as simple :( see - https://github.com/faros-ai/airbyte-connectors/pull/542

2024-01-24 21:08 UTC, omreego commented on Dockerfile
> +FROM node:21-alpine
Ah, good to know.
I'll try out the steps in #542

2024-01-25 19:16 UTC, tovbinm commented
I am not sure if nodejs is fully backward compatible. Folks, how can we test this?

2024-03-28 12:37 UTC, closed without merging