FAI-9758 - Jira Task Pull Request Source and Converter
faros-ai/airbyte-connectors pull request #1361
Opened 2024-03-05 18:21 UTC by matiaslcoulougian

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2024-03-07 13:55 UTC, chalenge requested changes
Let's only add what is needed for task pull request.

2024-03-07 13:55 UTC, chalenge commented on sources/jira-source/src/jira.ts
> +// TODO - Remove our models and use models in jira.js package
Can you only add the parts that are necessary for the task pull request? Do not want to just copy everything from the old source without re-thinking the code

2024-03-07 18:10 UTC, matiaslcoulougian commented
> Let's only add what is needed for task pull request.

Noted. I left all that was used in the `getIssues`, as we use than function for getting pull requests. But there is bunch of things we are not using yet e.g: assignee, additional fields, changelogs, sprint, etc... Currently we only need the issues key, updated and pull requests. Do you suggest reducing and simplifying it so we only have what we are currently using in `pull_requests` stream?

2024-03-07 19:28 UTC, chalenge commented
> > Let's only add what is needed for task pull request.
> 
> Noted. Removed a bunch but I left all that was used in the `getIssues`, as we use than function for getting pull requests. But most of issue things we are not using yet e.g: assignee, additional fields, changelogs, sprint, etc... Currently we only need the issues `key`, `updated` and `pull requests`. Do you suggest reducing and simplifying `getIssues` so we only have what we are currently using in `pull_requests` stream? @chalenge

Yes, let's make it minimal and fetch only needed fields for this part. Also helps make the review easier

2024-03-11 14:20 UTC, matiaslcoulougian commented on sources/jira-source/src/streams/pull_requests.ts
> +    return ['issue', 'updated'];
I think this is how we reference nested fields. [Documented](https://github.com/faros-ai/airbyte-connectors/blob/5fc8244e2dbb1b1125cefe1b0c0123821855bbcb/faros-airbyte-cdk/src/sources/streams/stream-base.ts#L81-L89) in `stream-base` `cursonField` function. (same for `primaryKey`)

2024-03-11 14:21 UTC, matiaslcoulougian commented on sources/jira-source/src/streams/pull_requests.ts
> +    return 'number';
Yes, true. If more than one issue reference to same PR, will have same number, so it can't be the PK

2024-03-11 14:21 UTC, matiaslcoulougian commented on sources/jira-source/src/streams/pull_requests.ts
> +    return 'number';
Any suggestions on what we should use?

2024-03-11 14:24 UTC, matiaslcoulougian commented on sources/jira-source/src/streams/pull_requests.ts
> +        ...currentStreamState,
We are overriding project new state using project key and maintaining same state for the other projects in the current stream state

2024-03-11 14:33 UTC, matiaslcoulougian commented on sources/jira-source/src/streams/pull_requests.ts
> +    return 'number';
Maybe composite key with `number` and `issue.key`?

2024-03-11 16:27 UTC, chalenge reviewed
Syncing pull requests should not be dependent on getting all the issue info and vice-versa. The pull requests stream should be in charge of fetching that from the API.

2024-03-11 16:27 UTC, chalenge commented on sources/jira-source/src/jira.ts
> +      async (item: any) => {
this should be de-coupled from getIssues. 
1. Issues streams should run to completion without worrying about pull requests.
2. We want to be able to independently sync tasks PRs from a list of Issues without fetching all the things.

2024-03-11 16:27 UTC, chalenge commented on sources/jira-source/src/jira.ts
> +    const fieldIds = [
For webhooks we should not need to fetch all these fields otherwise this defeats the purpose. I think for this pass we only need the issue keys/ids so we can fetch the PRs for those. We add some flag `fetchKeysOnly` if running for webhooks or minimal jira source or something of that sort.

2024-03-11 16:27 UTC, chalenge commented on destinations/airbyte-faros-destination/src/converters/jira/task_pull_requests.ts
> +// Required as dependency by Issues converter
what is the dependency / let's remove the dependency. These should run independently of each other

2024-03-11 16:27 UTC, chalenge commented on destinations/airbyte-faros-destination/src/converters/jira/task_pull_requests.ts
> +export class TaskPullRequests extends JiraConverter {
for consistency let's call this IssuePullRequests. We use `issue` everywhere else in the Jira source/converter

2024-03-11 16:27 UTC, chalenge commented on sources/jira-source/src/streams/task_pull_requests.ts
> +        if (issue.pullRequests) {
you can do to combine these two lines
```typescript
for (const pullRequest of issue.pullRequests || [])
```

2024-03-13 16:22 UTC, chalenge approved these changes
lgtm. Let's :shipit:

2024-03-13 16:35 UTC, merged