FAI-10607 - Add run_mode config to support WebhookGaps mode
faros-ai/airbyte-connectors pull request #1415
Opened 2024-04-12 12:39 UTC by matiaslcoulougian

## Description

Check for  WebhookGaps mode to select streams before records read.

TODO: 
- [ ] Add test case

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2024-04-12 13:54 UTC, ypc-faros commented on sources/jira-source/src/jira.ts
> +  readonly run_mode?: RunMode;
This needs to be added to the spec. See [here](https://github.com/faros-ai/airbyte-connectors/blob/3bd8555be7373f19f6b109776483442f93785c51/destinations/airbyte-faros-destination/resources/cloud.json#L31) for an example of an enum

2024-04-12 13:58 UTC, ypc-faros commented on sources/jira-source/src/streams/common.ts
> +  WebhookGaps = 'WebhookGaps',
nit: I don't love this name. Sounds too negative. What about `WebhookComplement`? cc/ @chalenge

2024-04-12 13:58 UTC, ypc-faros commented
Looking good! Let's add the test before merging...

2024-04-12 14:07 UTC, matiaslcoulougian commented on sources/jira-source/src/streams/common.ts
> +  WebhookGaps = 'WebhookGaps',
Like it better, trying to think some other alternatives...

2024-04-15 13:46 UTC, ypc-faros commented on sources/jira-source/resources/spec.json
Let's add `"airbyte_secret": true` to user/pass and token

2024-04-15 13:50 UTC, ypc-faros commented on sources/jira-source/resources/spec.json
nit: We don't need the `(optional)` in descriptions like `Username for authentication (optional)`
Airbyte properly renders the required and optional fields in the UI based on what's in `required`

2024-04-15 13:52 UTC, ypc-faros commented on sources/jira-source/resources/spec.json
> +          "WebhookGaps"
Also rename here => WebhookSupplement

2024-04-15 13:53 UTC, ypc-faros commented on sources/jira-source/test/index.test.ts
> +    expect(newCatalog.streams).toHaveLength(3);
ultra nit: Remove this length check. It's redundant given the `toMatchSnapshot` and it's going to be annoying to change it by hand every time we add a stream

2024-04-15 13:54 UTC, ypc-faros requested changes
A couple of final comments. We're almost there 🥳

2024-04-15 15:15 UTC, ypc-faros approved these changes

2024-04-15 15:25 UTC, merged