FAI-10152 - Sprint history record in sprint_reports stream
faros-ai/airbyte-connectors pull request #1426
Opened 2024-04-29 08:10 UTC by matiaslcoulougian

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2024-04-29 17:36 UTC, chalenge approved these changes
See comments

2024-04-29 17:36 UTC, chalenge commented on sources/jira-source/src/jira.ts
> +    includeIssues = true
when do we ever not want to include the report issues?

2024-04-29 17:36 UTC, chalenge commented on destinations/airbyte-faros-destination/test/converters/jira.test.ts
> +      tms_SprintHistory: 6,
in a separate PR let's start having real data objects written see [Asana tests](https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/test/converters/asana.test.ts#L122-L126)

2024-04-29 19:00 UTC, matiaslcoulougian commented on sources/jira-source/src/jira.ts
> +    includeIssues = true
For WebhookSupplement mode we only need the sprint report point fields, to write this fields in `sprint` record. `sprint_history` record will already be [populated](https://github.com/faros-ai/hermes/blob/20d3d52564e5bfc9ee71fbf59788b836503791b6/packages/worker/src/converters/jiraConverter.ts#L370) with webhook issue events.

2024-04-29 19:03 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/test/converters/jira.test.ts
> +      tms_SprintHistory: 6,
https://faros-ai.atlassian.net/browse/FAI-10982

2024-04-29 19:14 UTC, chalenge commented on sources/jira-source/src/jira.ts
> +    includeIssues = true
No, the [fields populated from the report](https://github.com/faros-ai/airbyte-connectors/pull/1426/files#diff-087c79ba42f4c18f101492fab2931ed8b6d7128048719e0479503a20598428a9R38-R40) are different from those that we get [from the issue changelog](https://github.com/faros-ai/hermes/blob/20d3d52564e5bfc9ee71fbf59788b836503791b6/packages/worker/src/converters/jiraConverter.ts#L429-L430)

2024-04-29 19:15 UTC, chalenge requested changes
We should sync the issue sprint report data

2024-04-29 19:26 UTC, matiaslcoulougian commented on sources/jira-source/src/jira.ts
> +    includeIssues = true
Missed that. Moving to fast 🙂

2024-04-30 13:33 UTC, chalenge approved these changes

2024-04-30 14:59 UTC, merged