FAI-11597: PR Reviews Source + Converter
faros-ai/airbyte-connectors pull request #1600
Opened 2024-07-23 12:30 UTC by matiaslcoulougian

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2024-07-24 15:11 UTC, dbruno21 commented on destinations/airbyte-faros-destination/package.json
> +    "test": "jest --verbose --color --updateSnapshot",
remove

2024-07-24 15:20 UTC, dbruno21 commented on sources/github-source/src/github.ts
>      private readonly fetchFiles: boolean,
fetchPullRequestFiles

2024-07-24 15:20 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +    private readonly fetchReviews: boolean,
fetchPullRequestReviews

2024-07-24 15:31 UTC, chalenge requested changes
Add the permissions needed for this stream

2024-07-24 15:31 UTC, chalenge commented on faros-airbyte-common/resources/github/queries/pull-request-reviews-query.gql
> +}
nit: new line

2024-07-24 15:31 UTC, chalenge commented on sources/github-source/package.json
> +    "test": "jest --verbose --color --updateSnapshot",
revert

2024-07-24 15:31 UTC, chalenge commented on sources/github-source/src/github.ts
> +        const reviews = this.fetchReviews
let's always return a list, could be empty and not have this other conditional

2024-07-24 15:31 UTC, chalenge commented on sources/github-source/src/github.ts
> +      const remainingReviews = await this.getPullRequestReviews(
what did do for PR Files? Kinda okay with graphQL here but let's have it consistent for other nested nodes

2024-07-24 15:31 UTC, chalenge commented on sources/github-source/src/github.ts
> +    return reviews;
if we think this maybe nullish then `return reviews ?? []` so we do not need to handle it in main code

2024-07-24 15:31 UTC, chalenge commented on sources/jira-source/package.json
> +    "test": "jest --verbose --color --updateSnapshot",
revert

2024-07-24 17:32 UTC, matiaslcoulougian commented on sources/github-source/src/github.ts
> +      const remainingReviews = await this.getPullRequestReviews(
For files we considered best using the rest API, cause the request returned all the fields we needed and we are avoiding getting nearer the GraphQL API rate limit. In this case opted by a graphql query cause the endpoint to list reviews by pr does not include comments count, meaning we would need to do +1 request to get this data and obtain the complete object.

2024-07-24 17:43 UTC, matiaslcoulougian commented on sources/github-source/src/github.ts
> +    return reviews;
Should not be nullish if they are no reviews. API returns an empty array

2024-07-25 18:53 UTC, dbruno21 commented on destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts
> +        model: 'vcs_PullRequestReview',
Add to destination models

2024-07-25 18:56 UTC, dbruno21 commented
@matiaslcoulougian What about vcs_PullRequestReviewRequest? Can create ticket and do on another PR

2024-07-25 19:03 UTC, dbruno21 commented on destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts
> +          reviewer: review.author
Each review author should be collected as we do for PR author
https://github.com/faros-ai/airbyte-connectors/blob/992b6d4a6ea0355abdbc127c85f8811ace079df1/destinations/airbyte-faros-destination/src/converters/github/faros_pull_requests.ts#L39

2024-07-25 20:15 UTC, matiaslcoulougian commented
> vcs_PullRequestReviewRequest

Missed it from the models included in this ticket. I will add in following PR 👍

2024-07-26 14:01 UTC, chalenge approved these changes
lgtm

2024-07-26 14:01 UTC, chalenge commented on sources/github-source/src/github.ts
> +    return reviews;
I had earlier seen us handling nullish condition in the main code

2024-07-26 14:52 UTC, matiaslcoulougian commented on sources/github-source/src/github.ts
> +    return reviews;
Maybe the condition was on the `fetchPullRequestReviews` flag. If that flag is off, we remove the reviews fragment for the query so pr.reviews will be null. But now we are directly checking for that `fetchPullRequestReviews` value: https://github.com/faros-ai/airbyte-connectors/pull/1600/files#diff-c3ec475eeb0ddb699ccf89b07eb40f24741bc8974d505f77035e1a8d27f4e563R286

2024-07-26 15:02 UTC, merged