FAI-13237 | GitHub Actions streams (source)
faros-ai/airbyte-connectors pull request #1725
Opened 2024-10-09 12:35 UTC by dbruno21

## Description

GitHub Actions streams (source)

Streams:
- Workflows
- Workflow Runs
- Workflow Jobs
- Artifacts

## Type of change
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change

## Related issues

## Migration notes

## Extra info

2024-10-15 13:44 UTC, matiaslcoulougian approved these changes
🚀

2024-10-15 18:02 UTC, chalenge requested changes
Let's memoize workflow run calls.

Also add documentation for authentication in README

2024-10-15 18:02 UTC, chalenge commented on sources/github-source/src/streams/faros_workflow_runs.ts
> +   * The API used by this stream always return records sorted by created_at in descending order.
is this documented anywhere or we found through testing?

2024-10-15 18:24 UTC, dbruno21 commented on sources/github-source/src/streams/faros_workflow_runs.ts
> +   * Reference: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits
e.g. If a run gets re-triggered on day 30 and it runs for 2 days, it takes 32 days.

2024-10-15 18:29 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +          ...omit(workflowRun, [
> recommends using pick

But pick works the opposite way.. We use omit here and every other place since we just want to remove a few fields that makes the written records to noise. e.g. user, repositories, organizations where we get lot of nested data that we don't need. I'm not sure having to pick every field one by one is worth it.

2024-10-15 18:30 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +const MAX_WORKFLOW_RUN_DURATION_MS = 35 * 24 * 60 * 60 * 1000; // 35 days
You already saw it on other comment

2024-10-15 18:33 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +    const createdSince = startDate
It's just because startDate / endDate it's optional here and other incremental method signatures. But yes, in theory, every usage will pass a startDate calculated from either state or cutoff.

2024-10-15 18:40 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +        this.updatedWorkflowRunsIds[key] = [
I was afraid that with lot of workflows runs per repo it would consume too much memory

2024-10-15 19:10 UTC, chalenge commented on sources/github-source/src/github.ts
> +          ...omit(workflowRun, [
I am mostly looking at the [documentation](https://lodash.com/docs/4.17.15#omit). The question is how much considerably slower it is. If we calling this 1000s of times then does that add up. I also generally prefer to get the fields we need in case API changes and adds more fields we do not care about

2024-10-15 19:14 UTC, dbruno21 commented on sources/github-source/src/streams/faros_artifacts.ts
> +  }
I don't think is worth it because we will be always be pulling jobs / artifacts from just updated workflow runs. So jobs and artifacts appearing here should be mostly new records + they shouldn't be a lot + we don't save requests (we could just skip writing a few records to destination)

2024-10-15 19:18 UTC, dbruno21 commented on sources/github-source/src/streams/faros_artifacts.ts
> +  get supportsIncremental(): boolean {
Are we sure? I thought (was told by @ypc-faros) that for cases like this and other streams (e.g. copilot seats) where we don't save a state we need to explicitly set this, so that destination models aren't reset when running the converter.

2024-10-15 19:18 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +        this.updatedWorkflowRunsIds[key] = [
Updated

2024-10-15 19:36 UTC, chalenge commented on sources/github-source/src/streams/faros_workflow_runs.ts
> +   * Reference: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits
I think "Each workflow run is limited to 35 days. " means from whenever it starts it can run for 35 days. Ok to use 35 days for a little leeway but think if someone starts a flow on day 30 and it runs for more than 5 days we won't get right state. Not sure though

2024-10-15 19:48 UTC, dbruno21 commented on sources/github-source/src/github.ts
> +          ...omit(workflowRun, [
Updated

2024-10-15 20:11 UTC, ypc-faros commented on sources/github-source/src/streams/faros_artifacts.ts
> +  get supportsIncremental(): boolean {
Yeah we need it (assuming you never want to delete old records from this stream)

2024-10-16 14:39 UTC, chalenge approved these changes
See comment

2024-10-16 15:05 UTC, merged