FAI-12709: Refactor Vanta Source to pull generic vulns + remediations
faros-ai/airbyte-connectors pull request #1759
Opened 2024-10-29 18:52 UTC by matiaslcoulougian

## Description
- Replace GraphQL Queries with generic vulnerability endpoints

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2024-11-15 23:59 UTC, chalenge requested changes
let's use the axios instance from `faros-js-utils`

2024-11-15 23:59 UTC, chalenge commented on destinations/airbyte-faros-destination/resources/cicdArtifactQueryByCommitSha.gql
> -  cicd_Artifact(where: {uid: {_in: $commitShas}}, limit: $limit, distinct_on: uid) {
isn't this more efficient instead of querying one by one?

2024-11-15 23:59 UTC, chalenge commented on destinations/airbyte-faros-destination/resources/vcsRepositoryQuery.gql
> +  vcs_Repository(where: {name: {_eq: $vcsRepoName}}, distinct_on: name) {
same as above

2024-11-15 23:59 UTC, chalenge commented on destinations/airbyte-faros-destination/src/converters/vanta/vulnerability_remediations.ts
> +  severityMap: {[key: string]: number} = {
can we document where these category values are coming from?

2024-11-15 23:59 UTC, chalenge commented on destinations/airbyte-faros-destination/src/converters/vanta/vulnerability_remediations.ts
> +  source = 'vanta';
is it vanta or Vanta?

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/resources/schemas/vulnerabilityRemediations.json
> +    "data": {}
add a proper spec

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/resources/spec.json
> +      "skip_connection_check": {
When do we ever not want to do this?

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/streams/vulnerabilities.ts
> +import {Vulnerability} from 'faros-airbyte-common/lib/vanta';
this should just be `from 'faros-airbyte-common/vanta';`

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/streams/vulnerability_remediations.ts
> +import {Vulnerability} from 'faros-airbyte-common/lib/vanta';
`from 'faros-airbyte-common/vanta';`

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +    // The expectation is that this token will last long enough to complete the connector.
How long does the token last? Let's add [token refresh interceptor](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/xray-source/src/xray.ts#L96)

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
>      const api = axios.create({
Let's use the faros utils [axioinstance](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/xray-source/src/xray.ts#L66) for retry logic.

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +    const api = axios.create({
we can re-use the axios instance created above and attach header as last thing [see example](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/xray-source/src/xray.ts#L94)

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +      throw new VError('Failed to fetch session token: %s', error);
use wrapApiError so we don't leak data

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +      const packed_response: AxiosResponse = await api.post(tokenUrl, body, {
```typescript
const response = await api...
```

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +        this.apiUrl + '/graphql',
unless we are using `this.apiUrl` for other things, let's remove it as class property and add baseUrl when we create the axiosInstance

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +    const url = `${this.apiUrl}v1/vulnerabilities`;
see comment above to attach `this.apiUrl` as baseUrl of instance

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
>    async getAxiosResponse(
Don't think we need this function if we use the faros axiosInstance. It already has retry logic backed in and/or we can pass [logic specific to this API](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/xray-source/src/xray.ts#L41-L65). 

Even if we need this function it will become cleaner

2024-11-15 23:59 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +        // Image tage scan won't be available if asset is a repository: https://developer.vanta.com/reference/listvulnerableassets#:~:text=has%20been%20scanned.-,imageScanTag,-string%20%7C%20null
some weird linting or line breaks

2024-11-15 23:59 UTC, chalenge commented on destinations/airbyte-faros-destination/src/converters/vanta/vulnerability_remediations.ts
> +          model: 'vcs_RepositoryVulnerability__Update',
Do we really need to query the graph for this? Would a blanket update without `relatedEntity.repository.name,` work? Is there any real risk when we do that?

2024-11-18 18:02 UTC, matiaslcoulougian commented on sources/vanta-source/resources/spec.json
> +      "skip_connection_check": {
Not sure... I think is not being used so we can remove it

2024-11-18 22:56 UTC, omreego commented on sources/vanta-source/resources/spec.json
> +      "skip_connection_check": {
I don't remember... we can remove this. I might have written it before a connection check was set up and I wanted to bypass it.

2024-11-18 23:02 UTC, matiaslcoulougian commented on sources/vanta-source/resources/spec.json
> +      "skip_connection_check": {
Removed 👍

2024-11-21 14:20 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/resources/cicdArtifactQueryByCommitSha.gql
> -  cicd_Artifact(where: {uid: {_in: $commitShas}}, limit: $limit, distinct_on: uid) {
It is but if we keep this we would need to save all vulnerability records we receive and process them all together on after read, to get all repos/artifacts with one query.

2024-11-21 14:20 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/resources/cicdArtifactQueryByCommitSha.gql
> -  cicd_Artifact(where: {uid: {_in: $commitShas}}, limit: $limit, distinct_on: uid) {
Added some maps to save fetched repos/artifacts and avoid querying them more than once

2024-11-25 16:49 UTC, chalenge reviewed
Looking great, see comments

2024-11-25 16:49 UTC, chalenge commented on destinations/airbyte-faros-destination/src/converters/vanta/vulnerability_remediations.ts
> +      {
Since each `sec_Vulnerability` is tied to either one let's figure out a way from the source what asset is and only update that

2024-11-25 19:28 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/src/converters/vanta/common.ts
> +  // Severity mapping from https://nvd.nist.gov/vuln-metrics/cvss
Added some TODOs marking the places we should move to common utility or use the ones you created here: https://github.com/faros-ai/airbyte-connectors/pull/1784. Will update after that PR is merged.

2024-11-28 16:25 UTC, chalenge approved these changes
lgtm, after addressing comment

2024-11-28 16:25 UTC, chalenge commented on destinations/airbyte-faros-destination/test/resources/vanta/vulnerability_records.log
> +{"record":{"stream":"mytestsource__vanta__vulnerabilities","emitted_at":1712020006067,"data":{"asset":{"imageTags":["e99a18c428cb38d5f260853678922e03abd8334f"],"name":"test-org/dolos","type":"CONTAIN
nit: newline

2024-11-28 16:25 UTC, chalenge commented on destinations/airbyte-faros-destination/test/resources/vanta/vulnerability_remediation_records.log
> +{"record":{"stream":"mytestsource__vanta__vulnerability_remediations","emitted_at":1712020006067,"data":{"asset": {"imageTags":["e99a18c428cb38d5f260853678922e03abd8334f"],"name":"test-org/dolos","ty
nit: newline

2024-11-28 16:25 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +    while (hasNext) {
this loop statement looks exactly the same as the one above, can you extract to shared function to make it DRYer

2024-11-28 16:25 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +    while (hasNext) {
see above

2024-11-28 16:25 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +          `Received 429 error from Vanta API, retrying in ${delay / 1000} seconds.`
`Received rate limit exceeded (429) error from Vanta API, retrying in ${delay / 1000} seconds.`

2024-11-28 16:25 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +          'Got 504 from Vanta API, sleeping for 30 seconds, then retrying.'
`Received gateway timeout (504), retrying 30 seconds`

2024-11-28 16:25 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +    const delayLogic = (
extract to separate function since it is a big function

2024-11-28 16:25 UTC, chalenge commented on sources/vanta-source/src/vanta.ts
> +        return 30000;
let's make this configurable

2024-11-28 18:46 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/src/converters/common/sec.ts
> +      default:
You are right. I added it with a previous logic I was implementing and forgot to remove it. We shouldn't default to 0.

2024-11-28 18:51 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/resources/cicdArtifactQueryByCommitSha.gql
> +query cicdArtifactQueryByCommitSha($commitShas: [String]) {
For getting all cicd artifacts related to the vulns we wrote and then be able to write cicd_ArtifactVulnerability. We need the full artifact key. Same with vcs_Repository

2024-11-28 18:56 UTC, matiaslcoulougian commented on destinations/airbyte-faros-destination/src/converters/vanta/vulnerability_remediations.ts
> +    return [];
We are currently not supporting `SERVER`, `SERVERLESS_FUNCTION`, `MANIFEST_FILE` and `WORKSTATION` asset types. Will add logging for this.

2024-12-02 18:30 UTC, chalenge commented
> good to go? @chalenge @omreego

We testing this. Hold on

2024-12-05 20:13 UTC, merged