Kelvin/add buildkite
faros-ai/airbyte-connectors pull request #190
Opened 2021-12-22 12:34 UTC by huongtn

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2021-12-27 12:28 UTC, Roma-Kyrnis commented
- Format JSON, GQL files.
- Add description to spec.json's properties.
- Remove commented code and `src/buildkite/resources` folder if it doesn't use. 
- I recommend to install "Code Spell Checker" extention. 
- Can you remove or use `organization` property in `getOrganizations` function
- Add incremental modes to streams. To pull incremental's builds you need to execute `getBuilds` function with needed params, as in [StatusPage](https://github.com/faros-ai/airbyte-connectors/blob/14ed3b24a62d43b99745892b8122809b673a806b/sources/statuspage-source/src/streams/incidents.ts#L41) cutoff option.
- You can pull `Builds` without calling `getPipelines` and `fetchPipelineBuilds`, The same for Jobs. Documentation to pull [Builds](https://buildkite.com/user/graphql/documentation/type/Viewer#:~:text=No%20description%20available.-,builds,-\(first%3A%20Int%2C%20last) and to pull [Jobs](https://buildkite.com/user/graphql/documentation/type/Viewer#:~:text=the%20current%20user-,jobs,-\(first%3A%20Int%2C%20after)
- To pull pipelines use organizations set in config as in [Phabricator example](https://github.com/faros-ai/airbyte-connectors/blob/14ed3b24a62d43b99745892b8122809b673a806b/sources/phabricator-source/resources/spec.json#L47) and add description like "You can pull pipelines to every organization or pull pipelines to organizations set in the config".

2021-12-29 09:06 UTC, Roma-Kyrnis reviewed
Execelent work!

There are some recommendations:
- We need use UpdatedAt column but not CreatedAt to sync streams on incremental mode. If UpdatedAt field doesn't exist we use only full_sync mode
- Comments

2021-12-29 14:02 UTC, Roma-Kyrnis requested changes
Can you solve test errors?

2021-12-29 14:02 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +        model: 'cicd_Job',
We need to push data according to Faros-canonical-models. Job is [cicd_BuildStep](https://github.com/faros-ai/canonical-models/blob/2c5721a8b0c73c37d339f4089e43e55adf048799/resources/models/cicd.gql#L36). 

Can you check other destination's converters to be similar to canonical models?

2021-12-29 14:02 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +          uid: build.uid,
Update uid, and for Organizations

2021-12-29 15:45 UTC, Roma-Kyrnis commented on sources/buildkite-source/acceptance-test-config.yml
> +  // TODO: Add incremental streams if exist
Recover deleted code. I mean remove comment and `incremental` if there are no incrementals streams

2021-12-29 15:48 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  private async errorWrapper<T>(func: () => Promise<T>): Promise<T> {
What do you think about [spaces, as here](https://github.com/faros-ai/airbyte-connectors/blob/14ed3b24a62d43b99745892b8122809b673a806b/sources/squadcast-source/src/squadcast.ts#L139) beetwen functions to more convient read code?

2021-12-29 15:50 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +        slug: organizationItem.slug,
Good!

2021-12-29 16:51 UTC, huongtn commented on sources/buildkite-source/buildkite.log
> +{"log":{"level":"INFO","message":"config: {\"token\":\"REDACTED\"}"},"type":"LOG"}
ok

2021-12-29 16:54 UTC, Roma-Kyrnis requested changes

2021-12-29 16:54 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/streams/builds.ts
> +    streamState?: Dictionary<any>
Can you add `type` or `interface` to `streamState`? In other streams too

2021-12-29 17:06 UTC, huongtn commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  readonly uid: string;
I think should use uuid as identify

2021-12-29 17:19 UTC, huongtn commented on sources/buildkite-source/acceptance-test-config.yml
> +  // TODO: Add incremental streams if exist
ok

2022-01-01 16:58 UTC, Roma-Kyrnis commented on sources/buildkite-source/test_files/spec.json
> +        "description": "organization slug. You can pull pipelines to every organization or pull pipelines to organizations",
Update text to clear why we need `organization` parameter and how connector will work without it

2022-01-01 17:46 UTC, Roma-Kyrnis requested changes
There are changes. Can you mention me if there is missunderstanding?

I'll clear the way to create source and destination's converter:
1.  First we pull data from source. We do it in sources folders. We just need to pull data but try to not change it. We can update data if we need: extra field (not defined on source stream) or update field names from snake-case to camel-case or etc. . In our case it's BuildKite.
2.  Next, we saving data to Faros canonical [models](https://github.com/faros-ai/canonical-models/tree/main/resources/models). For example we save [IncidentUpdates](https://github.com/faros-ai/airbyte-connectors/blob/14ed3b24a62d43b99745892b8122809b673a806b/destinations/faros-destination/src/converters/statuspage/incident_updates.ts#L27) on StatusPage. We use `ims_IncidentEvent` model to keep IncidentUpdate. In canonical models we have field `detail` but in StatusPage data we have field `body` than we save `body` to `detail`. Not all canonical model's fields can exist in source IncidentUpdate object than we can ommit those fields. But we cannot ommit [fields](https://github.com/faros-ai/canonical-models/blob/main/resources/models/ims.gql#:~:text=ims_IncidentEvent%20%40model\(key%3A-,%5B%22uid%22%2C%20%22incident%22%5D,-\)%20%7B) defined after model name in brackets.

2022-01-01 17:46 UTC, Roma-Kyrnis commented on sources/buildkite-source/resources/spec.json
> +        "airbyte_secret": false
Remove `airbyte_secret` variables with value `false`

2022-01-01 17:46 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/streams/pipelines.ts
> +    const lastUpdatedAt: Date = createdAt;
We need to use updated timestamp field from `latestRecord` if it exist in `Pipeline`. But createdAt field isn't updatedAt. Can you remove incremental mode from pipelines?

Even if we use `createdAt` field to incrementaly sync pipelines then we can catch a gap. Example, if We update Pipeline on BuildKite.com we will not see that pipeline was updating because we don't have updated timestamp field.

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/buildsteps.ts
> +export class BuildkiteBuilds extends BuildkiteConverter {
Rename this file to `jobs.ts` and update class name to `BuildkiteJobs`

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  readonly createdAt?: Date;
Update all Date fields to string type and in buildkite-source too. Because from BuildKite we get strings but not Date object

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/pipelines.ts
> +  convert(
Can you add space between functions?

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/pipelines.ts
> +        record: {
Update records to [cicd_Pipeline canonical model](https://github.com/faros-ai/canonical-models/blob/2c5721a8b0c73c37d339f4089e43e55adf048799/resources/models/cicd.gql#L12)

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/pipelines.ts
> +        record: {
`repo` and `source` fields are superfluous

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/buildsteps.ts
> +          source,
Can you remove superfluous field `source`?

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/buildsteps.ts
> +          type: job.type,
Update to [BuildType](https://github.com/faros-ai/canonical-models/blob/2c5721a8b0c73c37d339f4089e43e55adf048799/resources/models/cicd.gql#L135). You can find an example in other converters

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +          source,
Can you remove superfluous field?

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/organizations.ts
> +          uid: organization.id,
Let's use uuid as unique identifier as in other BuildKite's converters

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +          state: build.state,
Save BuildKite Build's `state` to Faros canonical models's `status`. But before convert it to `status` as in [Feeds](https://github.com/faros-ai/feeds/blob/e9693523158e14f4af587dd506cf1f0bc0d6189c/feeds/cicd/buildkite-feed/src/index.ts#L282)

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/buildsteps.ts
> +          state: job.state,
Update `state` to `status` as similar as in builds converter

2022-01-01 17:46 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/buildsteps.ts
> +          source,
Because it's not cleared by canonical model `[cicd_BuildStep](https://github.com/faros-ai/canonical-models/blob/2c5721a8b0c73c37d339f4089e43e55adf048799/resources/models/cicd.gql#L36)`

2022-01-01 22:31 UTC, huongtn commented on destinations/faros-destination/src/converters/buildkite/organizations.ts
> +          uid: organization.id,
Orgainization api reply id as uuid

2022-01-02 14:55 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/organizations.ts
> +          uid: organization.id,
Ok

2022-01-02 15:10 UTC, Roma-Kyrnis requested changes
Update destinations/faros-destination/test/resources/buildkite/all-streams.log file to fix error with tests

2022-01-02 15:10 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  readonly createdAt?: Date;
Update all Date types to string

2022-01-02 15:10 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  readonly createdAt?: Date;
The same as destination converter

2022-01-02 15:10 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +    let source: RepoSource;
remove or use `source` variable

2022-01-02 15:10 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +    endedAt?: Date;
Create interface to returned data

2022-01-02 15:10 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +    detail: string;
Create interfaces to returned data with 2 or more fields

2022-01-02 15:16 UTC, Roma-Kyrnis requested changes

2022-01-02 15:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/resources/spec.json
> +          "buildkite": {
Where do you use ApplicationMapping? Can you remove if it doen't need

2022-01-02 15:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  protected BuildkiteConfig(ctx: StreamContext): BuildkiteConfig {
Remove it if doesn't use in your BuildKite's converters

2022-01-02 15:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  protected applicationMapping(ctx: StreamContext): ApplicationMapping {
And this also

2022-01-02 15:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  protected BuildkiteConfig(ctx: StreamContext): BuildkiteConfig {
And below too

2022-01-02 15:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  static readonly MAX_DESCRIPTION_LENGTH = 1000;
Use it to `substring` descriptions or names in BuildKite's converters otherwise remove it

2022-01-02 15:16 UTC, Roma-Kyrnis commented on sources/buildkite-source/resources/spec.json
> +        "description": "You can pull pipelines to every organizations"
Update text. You can use questions: Why we need organization parameter? How the program will work without it?

2022-01-03 09:05 UTC, Roma-Kyrnis requested changes

2022-01-03 09:05 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
>        default:
You can update object here with default values to not use return twice

2022-01-03 09:05 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +      return {category: 'Custom', detail: 'undefined'} as JobState;
Remove `as JobState`. It doesn't need

2022-01-03 09:05 UTC, Roma-Kyrnis commented on sources/buildkite-source/resources/spec.json
> +        "description": "If set it will pull all pipelines from only this organization, If no it pull all pipelines from all organizations"
Great!

2022-01-03 09:18 UTC, Roma-Kyrnis requested changes

2022-01-03 09:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +      return {category: 'Unknown', detail: 'undefined'};
Can you use [enums](https://github.com/faros-ai/canonical-models/blob/2c5721a8b0c73c37d339f4089e43e55adf048799/resources/models/cicd.gql#L124) to set categories values?
An example from [StatusPage](https://github.com/faros-ai/airbyte-connectors/blob/14ed3b24a62d43b99745892b8122809b673a806b/destinations/faros-destination/src/converters/statuspage/incidents.ts#L105). Instead of using string values we can use enums

2022-01-03 09:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +      case 'JobTypeBlock':
Update to ENUM

2022-01-03 09:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +      case 'canceling':
Update to ENUM

2022-01-03 09:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +        return {category: 'Script', detail} as JobState;
Update to ENUM

2022-01-03 09:30 UTC, Roma-Kyrnis requested changes

2022-01-03 09:30 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +  convertBuildState(state: string | undefined): {
Move this function to BuildKiteCommon

2022-01-03 09:30 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/builds.ts
> +  extractRepo(repoUrl: string): RepoExtract | undefined {
Move this function to BuildKiteCommon

2022-01-03 09:30 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +  convertBuildStepTime(buildStep: Job): JobTime {
Move this function to BuildKiteCommon

2022-01-03 09:30 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +  convertBuildStepState(state: string | undefined): {
Move this function to BuildKiteCommon

2022-01-03 09:30 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +  convertBuildStepType(type: string): JobState {
Move this function to BuildKiteCommon

2022-01-05 08:40 UTC, Roma-Kyrnis requested changes

2022-01-05 08:40 UTC, Roma-Kyrnis commented on destinations/faros-destination/resources/spec.json
> +            "type": "object"
Remove this object. It doesn't use any properties to BuildKite

2022-01-05 08:40 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +    }
You can remove this `if` statement because you have `switch case` with the same `default` result

2022-01-05 08:40 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +      case JobType.JobTypeCommand:
I see that you are using `JobType` instead of `JobTime`. Is it Ok?

2022-01-05 08:40 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +    } as JobTime;
You can use `const result: JobTime = {...` instead of `as JobTime`

2022-01-05 08:40 UTC, Roma-Kyrnis commented on destinations/faros-destination/resources/spec.json
> +            "type": "object"
I mean `"buildkite": {
            "title": "Buildkite",
            "description": "Configuration options that apply to records generated by the Buildkite Source.",
            "type": "object"`

2022-01-05 08:43 UTC, Roma-Kyrnis requested changes

2022-01-05 08:43 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +export interface JobTime {
You can rename this object to `Timestamps` or etc. To use JobTime in `convertBuildStepTime` function

2022-01-05 13:53 UTC, huongtn commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +      case JobType.JobTypeCommand:
should be ok, I followed from feed
https://github.com/faros-ai/feeds/blob/master/feeds/cicd/buildkite-feed/src/index.ts#L425

2022-01-05 21:28 UTC, Roma-Kyrnis commented
Good job!

2022-01-05 22:45 UTC, Roma-Kyrnis requested changes
Update files in `schemas` folder simmilar to interfaces from `buildkite/buildkite.ts` file.
Use acceptance tests: `lerna run build && ./scripts/source-acceptance-test.sh buildkite-source`

2022-01-05 22:45 UTC, Roma-Kyrnis commented on sources/buildkite-source/resources/schemas/pipelines.json
> +            "type": "number"
Update to `string` type

2022-01-05 22:45 UTC, Roma-Kyrnis commented on sources/buildkite-source/resources/schemas/pipelines.json
> +            "type": "string"
Pipeline's descrption can be null, update type to `["string", "null"]`

2022-01-05 22:45 UTC, Roma-Kyrnis commented on sources/buildkite-source/test_files/expected_records.txt
> +{"stream":"organizations","emitted_at":1640336658662,"data":{"id":"f6a6499d-7a62-436d-9e1c-3c8fc3ed4f96","graphql_id":"T3JnYW5pemF0aW9uLS0tZjZhNjQ5OWQtN2E2Mi00MzZkLTllMWMtM2M4ZmMzZWQ0Zjk2","url":"htt
Update records

2022-01-06 02:01 UTC, huongtn commented on sources/buildkite-source/test_files/expected_records.txt
> +{"stream":"organizations","emitted_at":1640336658662,"data":{"id":"f6a6499d-7a62-436d-9e1c-3c8fc3ed4f96","graphql_id":"T3JnYW5pemF0aW9uLS0tZjZhNjQ5OWQtN2E2Mi00MzZkLTllMWMtM2M4ZmMzZWQ0Zjk2","url":"htt
Update what data?

2022-01-08 10:25 UTC, Roma-Kyrnis commented on sources/buildkite-source/test_files/expected_records.txt
> +{"stream":"organizations","emitted_at":1640336658662,"data":{"id":"f6a6499d-7a62-436d-9e1c-3c8fc3ed4f96","graphql_id":"T3JnYW5pemF0aW9uLS0tZjZhNjQ5OWQtN2E2Mi00MzZkLTllMWMtM2M4ZmMzZWQ0Zjk2","url":"htt
All stream to updated data from source

2022-01-08 10:26 UTC, Roma-Kyrnis requested changes

2022-01-08 10:26 UTC, Roma-Kyrnis commented on sources/buildkite-source/package.json
> +    "typescript-memoize": "^1.0.1",
Remove dependency if doen't use it

2022-01-08 10:26 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +import {Memoize} from 'typescript-memoize';
Remove or use Memoize funtion

2022-01-08 10:28 UTC, Roma-Kyrnis commented
Do you run acceptance-tests?
`lerna run build && ./scripts/source-acceptance-test.sh buildkite-source`

If you have an issue with it write to me I'll help you

2022-01-10 17:36 UTC, huongtn commented
@Roma-Kyrnis I can run acceptance-tests, please test on your local

2022-01-11 21:10 UTC, Roma-Kyrnis requested changes

2022-01-11 21:10 UTC, Roma-Kyrnis commented on sources/buildkite-source/resources_gql/builds-query.gql
> -query buildsQuery ($maxJobsPerBuild: Int){
Can we use `maxBuilds` ?

2022-01-11 21:14 UTC, Roma-Kyrnis commented
Acceptance tests are working! Good job!

2022-01-27 03:18 UTC, huongtn commented
@yevgenius what I need to update?

2022-02-02 03:00 UTC, yevgenius commented on sources/buildkite-source/resources/schemas/pipelines.json
> +}
can you add a formatting rule to have an empty line at the end of a file?

2022-02-05 07:44 UTC, tovbinm commented on sources/buildkite-source/test/index.test.ts
> +  // test('check connection', async () => {
please fix the tests

2022-02-06 11:14 UTC, huongtn commented on sources/buildkite-source/test/index.test.ts
> +  // test('check connection', async () => {
ok @tovbinm, I just back to work

2022-02-06 11:14 UTC, huongtn commented on sources/buildkite-source/resources/schemas/pipelines.json
> +}
ok @yevgenius

2022-02-07 09:49 UTC, huongtn commented on sources/buildkite-source/test/index.test.ts
> +  // test('check connection', async () => {
@tovbinm could you please advice what code should I follow?

2022-02-08 23:07 UTC, cjwooo commented
@huongtn Please resolve the merge conflicts.

2022-02-15 02:55 UTC, cjwooo commented on sources/buildkite-source/test_files/config.json
> +    "token": "87c0cd3efa703a3c1d03828290a93a79d1853c54"
Is this a real token?

2022-02-15 14:48 UTC, huongtn commented on sources/buildkite-source/test_files/config.json
> +    "token": "87c0cd3efa703a3c1d03828290a93a79d1853c54"
Correct

2022-02-16 01:54 UTC, cjwooo commented on sources/buildkite-source/test_files/config.json
> +    "token": "87c0cd3efa703a3c1d03828290a93a79d1853c54"
Remove this config from your PR. We don't want to include actual tokens in the repo.

2022-02-16 02:29 UTC, tovbinm commented
Also rotate the token. Assume it was exposed
-- 

-Matthew

2022-02-16 19:26 UTC, cjwooo commented
After rotating the token, use https://onetimesecret.com to send me the new token so we can include it in our testing workflow.

2022-02-21 07:38 UTC, Roma-Kyrnis requested changes
Update branch to main `git pull origin main`. If you have any suggestions or questions you can ask me)

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +      baseURL: `${REST_API_URL}`,
Add version of API to spec.json with default `v2` and update to `baseURL: '${REST_API_URL)/${REST_API_VERSION}'`. 
Name of variables choose by yourself

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test/index.test.ts
> +  // test('check connection', async () => {
Hi @huongtn you can follow Pagerduty connector

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test/index.test.ts
> +  });
Update to `beforeEach(() => {
    jest.clearAllMocks();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });` follow to Pagerduty connector

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test/index.test.ts
> +  // test('check connection', async () => {
To test sources we need to mock class or functions. Use `Buildkite.instance = jest.fn().mockImplementation(() => {
      return new Buildkite(undefined,{get: jest.fn().mockResolvedValue({})} as any, 10, 500, 'org');
    });` To mock BuildKite instance

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test/index.test.ts
> +  //   const source = new sut.BuildkiteSource(logger);
Also, we can mock BuildKite instance here to follow our test suits: `Buildkite.instance = jest.fn().mockImplementation(() => {
      return new Buildkite(undefined,{get: jest.fn().mockRejectedValue(new Error('some error'))} as any, 10, 500, 'org');
    });`

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test_files/abnormal_state.json
> +{
Can we remove this file?

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test_files/incremental_configured_catalog.json
> +{
In our case Organizations do not have update timestamp field. Do organization stream incremental? If no we can remove this file

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/test_files/full_configured_catalog.json
> +                    "full_refresh"
If organizations stream is incremental update `streams/organizations` file to be incremental and update catalog

2022-02-21 07:38 UTC, Roma-Kyrnis commented on sources/buildkite-source/package.json
> +  "dependencies": {
Update dependencies

2022-02-21 09:00 UTC, huongtn commented on sources/buildkite-source/test_files/full_configured_catalog.json
> +                    "full_refresh"
organizations stream is not incremental

2022-02-23 12:02 UTC, Roma-Kyrnis requested changes

2022-02-23 12:02 UTC, Roma-Kyrnis commented on sources/buildkite-source/test/index.test.ts
> +  test('check connection', async () => {
Also, add check connection if incorrect credentials, [example](https://github.com/faros-ai/airbyte-connectors/blob/14d77e6cbf484125ccc6842d7935587ea1c777ba/sources/pagerduty-source/test/index.test.ts#L53)

2022-02-23 13:21 UTC, huongtn commented on destinations/faros-destination/src/converters/buildkite/jobs.ts
> +    const build = {
They are should not be undefined

2022-02-28 21:18 UTC, Roma-Kyrnis requested changes

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/pipelines.ts
> +    const organization = {uid: pipeline.organization?.slug, source};
`if (!organization.uid) {
      return [];
    }`

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  readonly build?: {
I found why it shows an error. Does the interface show that the **pipeline** may not exist? Then it's better to check if it exists in the code, and if not, then return an empty array.
For example: `if (!job.build?.pipeline) {      return [];
    }`


Similar with other using parameters like pipeline, pipeline.slug, organization.slug and others. I think you can find them by yourself. I just try to show you where you need to search

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  readonly build?: {
Also, can you check if source return needed data?

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +    readonly pipeline?: {
I'm about this

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +      readonly organization?: {
I'm about this

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  readonly organization?: {
I'm about this

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +    slug?: string;
I'm about this

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +  readonly pipeline?: {
I'm about this

2022-02-28 21:18 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/buildkite/common.ts
> +      slug?: string;
I'm about this

2022-03-01 13:59 UTC, huongtn commented
Already test e2e

2022-03-02 20:08 UTC, Roma-Kyrnis commented
If it is possibly null or undefined, i.e. variables with the sign "?". It is better to check writing data, for example: `if (!job.build?.pipeline) { return []; }`

2022-03-03 19:10 UTC, cjwooo commented
Does the Buildkite API allow specifying dates in requests (e.g. for fetching jobs or builds) so that we can only fetch records after a certain date? This will enable using incremental streams.

2022-03-04 03:23 UTC, tovbinm commented
Yes, you can use cursors for it. See https://github.com/faros-ai/feeds/blob/master/feeds/cicd/buildkite-feed/src/buildkite.ts

2022-03-04 18:37 UTC, cjwooo commented
@huongtn Please update the builds and jobs streams to support incremental mode by adding a parameter to the GraphQL query to only pull records after a given timestamp, similar to how our feed operates.

2022-03-04 18:38 UTC, cjwooo commented
I've merged all the latest commits from the main branch into this one, be sure to pull before making changes.

2022-03-04 18:41 UTC, cjwooo requested changes

2022-03-04 18:41 UTC, cjwooo commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +    const data = await this.graphClient.request(BUILDS_QUERY, variables);
This and getJobs() should also paginate through all the pages of requests like you do for organization pipelines.

2022-03-04 18:41 UTC, cjwooo commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +      const res = await this.restClient.get<Organization[]>('organizations');
Please confirm that this api response isn't a paginated list.

2022-03-05 03:26 UTC, huongtn commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +      const res = await this.restClient.get<Organization[]>('organizations');
confirmed, here is reference
https://buildkite.com/docs/apis/rest-api/organizations

2022-03-05 03:32 UTC, huongtn commented
> 



> @huongtn Please update the builds and jobs streams to support incremental mode by adding a parameter to the GraphQL query to only pull records after a given timestamp, similar to how our feed operates.

GraphQL do not support parameter to only pull records after a given timestamp, we only query after "curser" field
for ex: jobs(first:10, after:"ktkhMjAyMS0xMi0yMCAwMzozNzo0MC44ODU1MzYwMDAgVVRD2SQ0NDNmNzFlZi1lMjY0LTQwNTEtYTA2Mi1lNmYyYjRlOTExNzA=")

2022-03-05 04:05 UTC, tovbinm commented
@huongtn Use cursor for incremental sync. See our Buildkite implementation in our internal feeds repository.

2022-03-06 09:42 UTC, huongtn commented
> @huongtn Use cursor for incremental sync. See our Buildkite implementation in our internal feeds repository.

@tovbinm  I saw our internal feeds repository have parameter "pipelineSlug", Do we need to add to connector?

2022-03-31 18:06 UTC, cjwooo requested changes

2022-03-31 18:06 UTC, cjwooo commented on sources/buildkite-source/test_files/abnormal_state.json
> +    "lastCursor": "ktkhMjAyMS0xMi0yMCAwMzoyMToyOC4wNDgxMDUwMDAgVVRD2SQ1ZjBhZmM1MC04YTcxLTQyMzUtYTE0Ny00ZmY4YmU5ZTM4Njg="
These cursors do not look right. They should be timestamp values for the most recently updated build/job, similar to what you did for the Bamboo source and others https://github.com/faros-ai/airbyte-connectors/pull/353/files#diff-8521ef7e247d0f45f37d3a9b71963d13839fc2cdb017827e489baa948facbe6dR3. The current cursors look like GraphQL query result cursors, which is not what we want.

2022-04-01 16:33 UTC, huongtn commented on sources/buildkite-source/test_files/abnormal_state.json
> +    "lastCursor": "ktkhMjAyMS0xMi0yMCAwMzoyMToyOC4wNDgxMDUwMDAgVVRD2SQ1ZjBhZmM1MC04YTcxLTQyMzUtYTE0Ny00ZmY4YmU5ZTM4Njg="
@cjwooo could you please share what is url document that build and job support incremental with timestamp?

2022-04-05 14:48 UTC, huongtn commented on sources/buildkite-source/test_files/abnormal_state.json
> +    "lastCursor": "ktkhMjAyMS0xMi0yMCAwMzoyMToyOC4wNDgxMDUwMDAgVVRD2SQ1ZjBhZmM1MC04YTcxLTQyMzUtYTE0Ny00ZmY4YmU5ZTM4Njg="
@cjwooo I update for build stream, but job does not support incremental with timestamp, here is reference: https://buildkite.com/user/graphql/documentation/type/Viewer

2022-04-07 18:04 UTC, cjwooo commented on sources/buildkite-source/test_files/abnormal_state.json
> +    "lastCursor": "ktkhMjAyMS0xMi0yMCAwMzoyMToyOC4wNDgxMDUwMDAgVVRD2SQ1ZjBhZmM1MC04YTcxLTQyMzUtYTE0Ny00ZmY4YmU5ZTM4Njg="
Can you use a builds query to get the jobs how the feed does it here https://github.com/faros-ai/feeds/blob/master/feeds/cicd/buildkite-feed/resources/pipeline-builds-query.gql where the jobs are fetched as part of the build?

2022-04-08 02:27 UTC, huongtn commented on sources/buildkite-source/test_files/abnormal_state.json
> +    "lastCursor": "ktkhMjAyMS0xMi0yMCAwMzoyMToyOC4wNDgxMDUwMDAgVVRD2SQ1ZjBhZmM1MC04YTcxLTQyMzUtYTE0Ny00ZmY4YmU5ZTM4Njg="
So just add jobs as data of build stream, no need job stream anymore right?

2022-04-11 16:17 UTC, cjwooo commented on sources/buildkite-source/test_files/abnormal_state.json
> +    "lastCursor": "ktkhMjAyMS0xMi0yMCAwMzoyMToyOC4wNDgxMDUwMDAgVVRD2SQ1ZjBhZmM1MC04YTcxLTQyMzUtYTE0Ny00ZmY4YmU5ZTM4Njg="
Yes that will work.

2022-04-14 15:22 UTC, cjwooo commented on sources/buildkite-source/src/streams/pipelines.ts
> +  get cursorField(): string | string[] {
Since pipelines cannot be queried incrementally, let's make this stream `full_refresh` only and return all the pipelines.

2022-04-14 15:22 UTC, cjwooo commented on README.md
> +<<<<<<< HEAD
Unresolved merge.

2022-04-15 01:57 UTC, cjwooo commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  async *getPipelines(cursor?: string): AsyncGenerator<Pipeline> {
Does this paginate through all the pipelines? We should be returning all the pipelines for this stream, not just the ones from a single page of results.

2022-04-15 01:59 UTC, cjwooo commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  async *getPipelines(cursor?: string): AsyncGenerator<Pipeline> {
Same for the other getXYZ functions.

2022-04-15 03:16 UTC, huongtn commented on sources/buildkite-source/src/buildkite/buildkite.ts
> +  async *getPipelines(cursor?: string): AsyncGenerator<Pipeline> {
It will loop to pull all pipelines

2022-04-21 01:55 UTC, cjwooo approved these changes

2022-04-21 01:55 UTC, merged