Kelvin/add shortcut
faros-ai/airbyte-connectors pull request #217
Opened 2022-01-05 16:13 UTC by huongtn

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-01-05 23:14 UTC, Roma-Kyrnis requested changes
Update streams with
 `cursorField` function  with updated timestamp field, as example ` 'updated_at';` in Iteration to incremental modes, similar as in [SquadCast](https://github.com/faros-ai/airbyte-connectors/blob/f5c3c482fb6133577921efb82db0c719643aad3a/sources/squadcast-source/src/streams/incidents.ts#L46)

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/buildkite-source/data.log
> +{"log":{"level":"INFO","message":"config: {\"token\":\"REDACTED\"}"},"type":"LOG"}
remove this file

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/resources/spec.json
> +        "default":"https://api.app.shortcut.com",
Add default to code too

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/resources/spec.json
> +        "default":"v3",
Add default to code too

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/shortcut.ts
> +    Shortcut.shortcut = new Shortcut(config);
create Shortcut class instance with config using default URL and version if it doesn't exist in config

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/spec.json
> +        "description":"Shortcut version",
Update or remove same description as title

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/spec.json
> +        "description":"Shortcut Base URL",
Update or remove same description as title

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/test/index.test.ts
> +  //     })
Update tests

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/incremental_configured_catalog.json
> +  "streams": [
Add all incremental streams

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/stories.ts
> +    syncMode === SyncMode.INCREMENTAL ? streamState?.lastUpdatedAt : undefined;
remove this line

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/repositories.ts
> +    syncMode === SyncMode.INCREMENTAL ? streamState?.lastUpdatedAt : undefined;
remove this line

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/projects.ts
> +    syncMode === SyncMode.INCREMENTAL ? streamState?.lastUpdatedAt : undefined;
remove this line

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/member.ts
> +    syncMode === SyncMode.INCREMENTAL ? streamState?.lastUpdatedAt : undefined;
remove this line

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/iterations.ts
> +    syncMode === SyncMode.INCREMENTAL ? streamState?.lastUpdatedAt : undefined;
remove this line

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/epics.ts
> +    syncMode === SyncMode.INCREMENTAL ? streamState?.lastUpdatedAt : undefined;
remove this line

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/shortcut.ts
> +export interface Story {
Remove interface and export from library

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/epics.ts
> +import {Epic} from 'clubhouse-lib';
export from shortcut/shortcut.ts

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/iterations.ts
> +import {Iteration} from 'clubhouse-lib';
export from shortcut/shortcut.ts

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/member.ts
> +import {Member} from 'clubhouse-lib';
export from shortcut/shortcut.ts

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/projects.ts
> +import {Project} from 'clubhouse-lib';
export from shortcut/shortcut.ts

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/repositories.ts
> +import {Repository} from 'clubhouse-lib';
export from shortcut/shortcut.ts

2022-01-05 23:14 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/epics.ts
> +    projectIds?: ReadonlyArray<number>
Where the projectIds inserting to function? You can use projects similar to `[Bitbucket's repositories](https://github.com/faros-ai/airbyte-connectors/blob/34743d1dc97da71ed51748c54160ef25e544d69f/sources/bitbucket-source/src/index.ts#L53)`

2022-01-05 23:15 UTC, Roma-Kyrnis commented
Test it with acceptance tests, similar to BuildKite

2022-01-06 03:55 UTC, huongtn commented
>

2022-01-06 06:25 UTC, tovbinm commented on destinations/faros-destination/src/converters/shortcut/stories.ts
> +          category: this.getTaskStatus(story),
Not required.

2022-01-06 08:42 UTC, huongtn commented on destinations/faros-destination/src/converters/shortcut/stories.ts
> +          category: this.getTaskStatus(story),
ok noted

2022-01-06 09:22 UTC, huongtn commented on sources/shortcut-source/resources/spec.json
> +        "default":"https://api.app.shortcut.com",
Set in getStorieByProjectId already

2022-01-06 09:22 UTC, huongtn commented on sources/shortcut-source/resources/spec.json
> +        "default":"v3",
Set in getStorieByProjectId already

2022-01-06 09:36 UTC, huongtn commented on destinations/faros-destination/src/converters/shortcut/common.ts
> +enum SprintState {
What do you mean? for SprintState or TaskStatusCategory?

2022-01-08 10:33 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/shortcut/common.ts
> +enum SprintState {
I mean all `types`, `enums` and `interfaces` move to `shortcut_models.ts` file

2022-01-08 10:46 UTC, Roma-Kyrnis requested changes
Do you have any issues with acceptance tests?

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/data.log
> +{"log":{"level":"INFO","message":"config: {\"token\":\"REDACTED\",\"base_url\":\"https://api.app.shortcut.com\",\"version\":\"v3\"}"},"type":"LOG"}
remove this file

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/shortcut.ts
> +    this.baseUrl = cfg.base_url ? cfg.base_url : 'https://api.app.shortcut.com';
create default variable for url

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/shortcut.ts
> +    this.version = cfg.version ? cfg.version : 'v3';
create default variable for version

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/shortcut.ts
> +export interface Story {
If you are adding additional fields you can do as `export interface Story extends StoryFromShortCutLibrary { ...additional fields...}`

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/full_configured_catalog.json
> +{
Update this file with current `catalog` returned from source

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/epics.ts
> +  }
Add `streamSlices` funciton as an [example](https://github.com/faros-ai/airbyte-connectors/blob/34743d1dc97da71ed51748c54160ef25e544d69f/sources/bitbucket-source/src/streams/pipeline_steps.ts#L31)

2022-01-08 10:46 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/epics.ts
> +    yield* shortcut.getEpics(this.projectIds);
Use `projectID` from `streamSlice`, an [example](https://github.com/faros-ai/airbyte-connectors/blob/34743d1dc97da71ed51748c54160ef25e544d69f/sources/bitbucket-source/src/streams/pipeline_steps.ts#L51)

2022-01-11 21:13 UTC, Roma-Kyrnis requested changes

2022-01-11 21:13 UTC, Roma-Kyrnis commented on sources/okta-source/data.log
> +{"record":{"stream":"users","emitted_at":1641627744274,"data":{"id":"00u3jaazzxOxur0Bp5d7","status":"STAGED","created":"2022-01-08T06:50:58.000Z","activated":null,"statusChanged":null,"lastLogin":nul
remove file

2022-01-11 21:13 UTC, Roma-Kyrnis commented on sources/shortcut-source/data.log
> -{"log":{"level":"INFO","message":"config: {\"token\":\"REDACTED\",\"base_url\":\"https://api.app.shortcut.com\",\"version\":\"v3\"}"},"type":"LOG"}
remove file

2022-01-11 22:10 UTC, Roma-Kyrnis requested changes
Update your settings in VSCode to add empty last line at the end of all files, [example](https://stackoverflow.com/questions/44704968/visual-studio-code-insert-new-line-at-the-end-of-files)

2022-01-11 22:10 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/streams/iterations.ts
> +          : currentStreamState?.lastUpdatedAt,
Update to:
`lastUpdatedAt:
        lastUpdatedAt >= new Date(currentStreamState?.lastUpdatedAt || 0)
          ? latestRecord.updated_at
          : currentStreamState.lastUpdatedAt,`

2022-01-11 22:10 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/abnormal_state.json
> +    "lastUpdatedAt": 1735718400000
update value to `"2025-01-01T00:00:00Z"`

2022-01-11 22:10 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/expected_records.txt
> +{"stream":"epics","emitted_at":1641863985324,"data":{"app_url":"https://app.shortcut.com/cntship/epic/13","archived":false,"started":true,"entity_type":"epic","labels":[],"mention_ids":[],"member_men
Remove `Epic` stream if it doesn't return from Shortcut source

2022-01-11 22:10 UTC, Roma-Kyrnis commented on sources/shortcut-source/test_files/incremental_configured_catalog.json
> +{
Update similar to:
`{
  "streams": [
    {
      "stream": {
        "name": "iterations",
        "json_schema": {},
        "supported_sync_modes": [
          "full_refresh",
          "incremental"
        ],
        "source_defined_cursor": true,
        "source_defined_primary_key": [
          [
            "id"
          ]
        ],
        "cursor_field": [
          "updated_at"
        ]
      },
      "sync_mode": "incremental",
      "destination_sync_mode": "append"
    }
  ]
}
`

2022-01-11 22:10 UTC, Roma-Kyrnis commented on sources/shortcut-source/acceptance-test-config.yml
> +      expect_records:
Add line `      empty_streams: ["epics"]
`

2022-01-11 22:10 UTC, Roma-Kyrnis commented on sources/shortcut-source/acceptance-test-config.yml
> +      expect_records:
On the same level as expect_records and config_path

2022-01-11 22:46 UTC, huongtn commented on sources/shortcut-source/test_files/expected_records.txt
> +{"stream":"epics","emitted_at":1641863985324,"data":{"app_url":"https://app.shortcut.com/cntship/epic/13","archived":false,"started":true,"entity_type":"epic","labels":[],"mention_ids":[],"member_men
These data return from Shortcut source, because I added new epic on my account

2022-01-11 22:46 UTC, huongtn commented on sources/shortcut-source/acceptance-test-config.yml
> +      expect_records:
stream Epics should have data

2022-01-11 23:11 UTC, huongtn commented
Now can run acceptance, thank @Roma-Kyrnis

2022-01-26 14:41 UTC, Roma-Kyrnis requested changes
Add component's shortcut in README.md file in the root folder. Add REAMDME.md and bootstrap.md in shortcut-source folder, example [SquadCast](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/squadcast-source/README.md)

2022-01-26 14:41 UTC, Roma-Kyrnis commented on sources/shortcut-source/src/shortcut.ts
> +  async *getStories(updateRange?: [Date, Date]): AsyncGenerator<ExtendStory> {
Where `getStories` func calling with updateRange param?

2022-01-27 18:17 UTC, Roma-Kyrnis commented
Kelvin, Can you update tests to resolve error?

2022-02-08 23:08 UTC, cjwooo commented
@huongtn Please resolve the merge conflicts. You can simply delete the package-lock.json and re-run `npm i` and that shouldn't get it up to date.

2022-02-09 07:37 UTC, huongtn commented
>

2022-02-09 07:38 UTC, huongtn commented
> @huongtn Please resolve the merge conflicts. You can simply delete the package-lock.json and re-run `npm i` and that should get it up to date.

@cjwooo done, please help check if ok?

2022-02-15 02:59 UTC, cjwooo commented
@huongtn Please slack me the config.json you used to run the source acceptance tests. Use https://onetimesecret.com/ to secure the secret and send me the url.

2022-02-16 19:23 UTC, cjwooo commented on sources/shortcut-source/src/shortcut.ts
> +  async *getStories(updateRange?: [Date, Date]): AsyncGenerator<ExtendStory> {
^^ @huongtn ? It looks like the `stories` stream is not an incremental stream but you have logic here to support pullling stories based on date range.

2022-02-16 19:25 UTC, cjwooo commented on sources/shortcut-source/test/index.test.ts
> +  // test('check connection', async () => {
Enable these tests. You can use https://github.com/faros-ai/airbyte-connectors/blob/main/sources/bitbucket-source/test/index.test.ts or https://github.com/faros-ai/airbyte-connectors/blob/main/sources/pagerduty-source/test/index.test.ts as a guideline.

2022-03-01 13:59 UTC, huongtn commented
Already test e2e

2022-03-06 13:34 UTC, Roma-Kyrnis requested changes

2022-03-08 20:14 UTC, merged