Resolve locations in Faros Destination for Google Calendar events
faros-ai/airbyte-connectors pull request #225
Opened 2022-01-08 10:07 UTC by Roma-Kyrnis

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix #216 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-01-08 18:46 UTC, tovbinm commented on README.md
> +GoogleCalendar Source | [sources/googlecalendar-source](sources/googlecalendar-source) | `docker pull farosai/airbyte-googlecalendar-source` | [![](https://img.shields.io/github/v/tag/faros-ai/airbyt
it's already on the list. remove this.

2022-01-08 18:48 UTC, tovbinm commented on destinations/faros-destination/src/converters/googlecalendar/calendar_models.ts
> +interface Location {
you dont need to redefine the types. they are already exported from the feeds-sdk

2022-01-08 18:48 UTC, tovbinm commented on destinations/faros-destination/src/converters/googlecalendar/calendar_models.ts
> +interface Location {
just import them from there

2022-01-08 18:51 UTC, tovbinm commented on destinations/faros-destination/src/converters/googlecalendar/calendar_models.ts
> +const location_geocode: Location = {
move the test value to test folder

2022-01-08 18:53 UTC, tovbinm commented on sources/googlecalendar-source/acceptance-test-config.yml
> +      # ignored_fields:
??

2022-01-08 18:54 UTC, tovbinm requested changes
Geocode API invocation should be done in Faros Destination, and not in Google Calendar source. https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/faros-destination/src/converters/googlecalendar/events.ts#L77

2022-01-09 07:51 UTC, Roma-Kyrnis commented on README.md
> +GoogleCalendar Source | [sources/googlecalendar-source](sources/googlecalendar-source) | `docker pull farosai/airbyte-googlecalendar-source` | [![](https://img.shields.io/github/v/tag/faros-ai/airbyt
removed

2022-01-09 07:56 UTC, Roma-Kyrnis commented on sources/googlecalendar-source/acceptance-test-config.yml
> +      # ignored_fields:
I'll remove this line

2022-01-09 08:00 UTC, Roma-Kyrnis commented
Ok. I'll remove Geocode from source.

Where do i use the async function to pull Geocode in destination's converter?

2022-01-10 17:40 UTC, tovbinm commented
suppressed by https://github.com/faros-ai/airbyte-connectors/pull/230

2022-01-10 17:40 UTC, closed without merging

2022-01-10 17:41 UTC, tovbinm commented
@Roma-Kyrnis please pick up the work on https://github.com/faros-ai/airbyte-connectors/pull/230 and finish it up.