Kelvin/add okta
faros-ai/airbyte-connectors pull request #231
Opened 2022-01-13 16:01 UTC by huongtn

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-01-26 16:45 UTC, Roma-Kyrnis requested changes
Try to run write to Faros-destination. Because there are errors when writting

2022-01-26 16:45 UTC, Roma-Kyrnis commented on sources/okta-source/src/streams/groups.ts
> +    return ['id', 'source'];
remove 'source' because Group doesn't have this field

2022-01-26 16:45 UTC, Roma-Kyrnis commented on sources/okta-source/src/streams/users.ts
> +    return ['id', 'source'];
remove 'source' because User doesn't have this field

2022-01-26 16:45 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/okta/models.ts
> +  lastUpdated: Date;
I see that in `expected_records.log` all Date fields has type string. Update all Date to string type

2022-01-26 16:45 UTC, Roma-Kyrnis commented on sources/okta-source/test_files/config.json
> +{
remove this file because there are secret credentials

2022-01-26 16:45 UTC, Roma-Kyrnis commented on sources/okta-source/acceptance-test-config.yml
> +    - config_path: "test_files/config.json"
Update path to config to `secrets/config.json` and in all fields below

2022-01-26 16:45 UTC, Roma-Kyrnis commented on sources/okta-source/test/index.test.ts
> +  });
Update test file to be the same as in other sources

2022-01-26 16:45 UTC, Roma-Kyrnis commented
Resolve conflicts

2022-02-02 20:22 UTC, tovbinm commented on destinations/faros-destination/src/converters/okta/groups.ts
> +        parentTeam: '',
1. Is there no `parentTeam` in Okta?
2. What about `?teamChain`

2022-02-02 20:24 UTC, tovbinm commented on sources/okta-source/test/index.test.ts
> +  // test('check connection', async () => {
Please finish up the tests

2022-02-03 05:28 UTC, yevgenius commented on destinations/faros-destination/src/converters/okta/groups.ts
> +        parentTeam: '',
I checked the API, and it doesn't appear to have any hierarchical information. Just [groups](https://developer.okta.com/docs/reference/api/groups/#list-groups) and users in the group

2022-02-03 06:19 UTC, tovbinm commented on destinations/faros-destination/src/converters/okta/groups.ts
> +        parentTeam: '',
thanks!

2022-02-03 06:20 UTC, tovbinm commented on destinations/faros-destination/src/converters/okta/groups.ts
> +        parentTeam: '',
So groups cannot contain other groups?

2022-02-03 18:34 UTC, willmarks commented on sources/okta-source/test_files/spec.json
> +        "title": "Each account have one domain ame",
nit: `name`

2022-02-03 21:05 UTC, merged