Kelvin/add backlog
faros-ai/airbyte-connectors pull request #235
Opened 2022-01-22 05:08 UTC by huongtn

## Description

> Add backlog connector

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-01-22 05:11 UTC, huongtn commented
@tovbinm currently each projects have many versions, milestones and each issues(tasks) have many versions, milestones.
So can I map  versions, milestones to tms_Sprint and tms_Release?

2022-01-27 13:14 UTC, Roma-Kyrnis requested changes
I'm trying to write to Faros-destination but got an Axios error. Can you test writting to Faros-destination?

Can you test using acceptance-test? I've got an error running test

2022-01-28 03:14 UTC, huongtn commented on destinations/faros-destination/src/converters/backlog/common.ts
> +  static readonly MAX_DESCRIPTION_LENGTH = 1000;
Could you please share Agile Accelerator pull request link?

2022-01-28 03:19 UTC, huongtn commented on sources/backlog-source/test_files/full_configured_catalog.json
> +{
Currently already get from command, what is your side?

2022-02-05 07:43 UTC, tovbinm commented on sources/backlog-source/test/index.test.ts
> +  // test('check connection', async () => {
please fix the tests

2022-02-15 03:00 UTC, cjwooo commented
@huongtn Please slack me the config.json you used to run the source acceptance tests. Use https://onetimesecret.com/ to secure the secret and send me the url.

2022-02-15 14:45 UTC, huongtn commented
> @huongtn Please slack me the config.json you used to run the source acceptance tests. Use https://onetimesecret.com/ to secure the secret and send me the url.

ok sure

2022-03-01 13:59 UTC, huongtn commented
Already test e2e

2022-03-06 18:16 UTC, Roma-Kyrnis requested changes
Update to main branch similar to BuildKite

2022-03-06 18:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/backlog/projects.ts
> +          description: versionMilestone.description,
Use subString to cut description to default length

2022-03-06 18:16 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/backlog/projects.ts
> +            description: versionMilestone.description,
And here also: Use subString to cut description to default length

2022-03-07 02:59 UTC, huongtn commented on sources/backlog-source/src/backlog.ts
> +      if (!lastUpdatedAt || new Date(item.updated) >= startTime) {
Because updatedSince only for Date, we need to check both Date and Time

2022-03-08 17:56 UTC, cjwooo approved these changes

2022-03-08 17:58 UTC, merged