Add Docker connector
faros-ai/airbyte-connectors pull request #264
Opened 2022-02-07 15:12 UTC by Roma-Kyrnis

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix #238

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-02-08 23:16 UTC, cjwooo requested changes

2022-02-08 23:16 UTC, cjwooo commented on destinations/faros-destination/resources/spec.json
> +                "description": "The images with the listed tags will be ignored by the feed. Must be a comma separated list."
The wording is a bit confusing here. It's expecting an array but the description says comma-separated list?

2022-02-08 23:16 UTC, cjwooo commented on destinations/faros-destination/resources/spec.json
> +                "description": "The images with the listed tags will be ignored by the feed. Must be a comma separated list."
In airbyte UI, you enter an array into the text field by pressing enter after each item.

2022-02-08 23:16 UTC, cjwooo commented on destinations/faros-destination/src/converters/docker/tags.ts
> +        `kipped artifact in repo ${repositoryKey.uid} (uid: ${tag.name})`
Typo `kipped` => `skipped`.

2022-02-08 23:16 UTC, cjwooo commented on sources/docker-source/test_files/spec.json
> +        "default": "tags/list"
NIT: I think it'd look better if this were `/tags/list`.

2022-02-08 23:31 UTC, cjwooo commented
@Roma-Kyrnis Please resolve merge conflicts. (Can simply delete package-lock.json and recreate with `npm i`).

2022-02-08 23:31 UTC, cjwooo commented on destinations/faros-destination/test/converters/docker.test.ts
> +    await mockttp.start({startPort: 30000, endPort: 50000});
The logic for the faros destination has changed a bit with regards to config validation. Please change this line to https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/faros-destination/test/converters/okta.test.ts#L23. I've updated the existing converter tests.

2022-02-15 10:35 UTC, Roma-Kyrnis commented on destinations/faros-destination/src/converters/docker/tags.ts
> +        `kipped artifact in repo ${repositoryKey.uid} (uid: ${tag.name})`
Thank you. I'll check next time text

2022-02-15 10:51 UTC, Roma-Kyrnis commented on destinations/faros-destination/test/converters/docker.test.ts
> +    await mockttp.start({startPort: 30000, endPort: 50000});
Ok, I'll change

2022-03-03 21:12 UTC, cjwooo approved these changes

2022-03-03 21:12 UTC, merged