Kelvin/add azure active directory
faros-ai/airbyte-connectors pull request #268
Opened 2022-02-09 13:31 UTC by huongtn

## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-03-01 13:58 UTC, huongtn commented
Already test e2e

2022-03-01 13:59 UTC, huongtn commented
Already test e2e

2022-03-17 08:07 UTC, Roma-Kyrnis requested changes
Add README.md file to azureactivedirectory-source folder and add source to root README.md file

2022-03-17 08:07 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/src/streams/groups.ts
> +  ): AsyncGenerator<Dictionary<any, string>, any, unknown> {
For User stream too

2022-03-17 08:07 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/acceptance-test-config.yml
> +      spec_path: "secrets/spec.json"
Update spec_path to `resources/spec.json`

2022-03-17 09:04 UTC, huongtn commented on sources/azureactivedirectory-source/src/azureactivedirectory.ts
> +      const request = require('request');
I tried to use this one but not working

2022-03-17 09:29 UTC, huongtn commented on destinations/airbyte-faros-destination/src/converters/azureactivedirectory/groups.ts
> +        parentTeam: {uid: 'all_teams'}, // TODO: compute parent team
I follow Okta source, that is added by Matthew

2022-03-17 10:02 UTC, huongtn commented on sources/azureactivedirectory-source/src/azureactivedirectory.ts
> +      if (extraUserInfo.status === 200) {
Will got issue if not check status == 200

2022-03-20 13:03 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/src/azureactivedirectory.ts
> +      const request = require('request');
I'll try to do it and let you know about result

2022-03-20 13:03 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/src/azureactivedirectory.ts
> +      if (extraUserInfo.status === 200) {
Ok

2022-03-20 13:05 UTC, Roma-Kyrnis commented on destinations/airbyte-faros-destination/src/converters/azureactivedirectory/groups.ts
> +        parentTeam: {uid: 'all_teams'}, // TODO: compute parent team
Okay

2022-03-20 13:07 UTC, Roma-Kyrnis commented on destinations/airbyte-faros-destination/src/converters/azureactivedirectory/users.ts
> +        location: {uid: user.streetAddress, source},
I mean write location model. res.push({ model: 'geo_Location...',})

2022-03-20 13:12 UTC, Roma-Kyrnis requested changes
Fix destination test

2022-03-20 13:12 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/test_files/full_configured_catalog.json
> +        "source_defined_primary_key": [
Update primary keys

2022-03-23 19:40 UTC, Roma-Kyrnis requested changes
There are some issues. Can we fix them? 
First, when run acceptance-test, it throws: `AssertionError: Some of defined cursor fields ['renewedDateTime'] are not specified in discover schema properties for groups stream   E           assert {}`

Second, while writing geo_Location to Faros in users converter

2022-03-23 19:40 UTC, Roma-Kyrnis requested changes

2022-03-23 19:40 UTC, Roma-Kyrnis commented on destinations/airbyte-faros-destination/src/converters/azureactivedirectory/users.ts
> +        address: user.streetAddress,
Write geo_Address model too

2022-03-23 19:41 UTC, Roma-Kyrnis commented on destinations/airbyte-faros-destination/src/converters/azureactivedirectory/users.ts
> +        address: user.streetAddress,
https://github.com/faros-ai/canonical-models/blob/main/resources/models/geo.gql

2022-03-24 03:03 UTC, huongtn commented
> There are some issues. Can we fix them? First, when run acceptance-test, it throws: `AssertionError: Some of defined cursor fields ['renewedDateTime'] are not specified in discover schema properties for groups stream E assert {}`
> 
> Second, while writing geo_Location to Faros in users converter

ok I fixed

2022-03-24 08:39 UTC, Roma-Kyrnis approved these changes

2022-03-24 17:47 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/src/azureactivedirectory.ts
> +      const request = require('request');
We can use Axios request with querystring params. `[Example](https://stackoverflow.com/questions/67502700/axios-returns-404-for-a-post-request-with-form-data)`

2022-03-27 22:00 UTC, Roma-Kyrnis requested changes

2022-03-29 14:36 UTC, Roma-Kyrnis commented on sources/azureactivedirectory-source/src/azureactivedirectory.ts
> +    const data = new URLSearchParams({
Great job!

2022-03-30 18:41 UTC, merged

2022-03-30 19:09 UTC, tovbinm commented
@cjwooo we might need to bump the version