Add Gitlab CI source
faros-ai/airbyte-connectors pull request #367
Opened 2022-04-06 10:02 UTC by matussmutny

## Description

Added new source for Gitlab CI
credentials and streams according to [Gitlab CI v1 connector](https://github.com/faros-ai/feeds/tree/master/feeds/cicd/gitlabci-feed)

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

Airbyte UI
![image](https://user-images.githubusercontent.com/86728131/161950637-baedbef8-5e77-4fc5-a664-26a72ad006fa.png)

2022-04-07 17:17 UTC, willmarks approved these changes

2022-04-08 12:29 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      yield buildGroup(group);
`subGroupPath` is constructed from part of `projectPathArray`, which is constructed from `group.full_path` and `projectName` and `subGroupPath` is actually `projectPathArray` without project name so actually group.full_path.

When I think about it now, it doesn't make really sense and I probably misunderstood config (group name or project names).

I don't know if I should direct this question to you, but if there is a subgroup, the config should look like this:
`groupName: "group"`
`projects: ["subgroup/project1", "subgroup/project2"]`
or like this:
`groupName: "group/subgroup"`
`projects: ["project1", "project2"]`

2022-04-08 12:29 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      throw new VError('token must be not an empty string');
[a54de8f](https://github.com/faros-ai/airbyte-connectors/pull/367/commits/a54de8f11e40970cdeb0c60aea7d75f5f168f58b)

2022-04-08 12:29 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      throw new VError('group name must be not an empty string');
[a54de8f](https://github.com/faros-ai/airbyte-connectors/pull/367/commits/a54de8f11e40970cdeb0c60aea7d75f5f168f58b)

2022-04-08 13:36 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +        yield buildJob(job);
Well, in [v1 version](https://github.com/faros-ai/feeds/blob/2f7e2745981596b284b54e4d12d99dadba6c06ab/feeds/cicd/gitlabci-feed/src/gitlab.ts#L115) they are not paginated but I checked [API docs](https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs) and API result is paginated so I will paginate them as pipelines

2022-04-08 17:04 UTC, willmarks commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      yield buildGroup(group);
Hmm this is tricky because I was hoping that we would be able to support all scenarios. However, in scenario 1, group information is contained in the project which is currently not available to this function. I think we want to retrieve all the subgroups as well as the passed group (groupName) which means that we probably need to pass the project information into this function.

There seem to be 4 scenarios:
#### 1 (all subgroup information is in the project)
```
groupName: "group"
projects: ["subgroup/project1"]

correct path: group/subgroup
```

#### 2 (all subgroup information is in the groupName)
```
groupName: "group/subgroup"
projects: ["project1"]

correct path: group/subgroup
```

#### 3 (subgroup information is in both groupName and project)
```
groupName: "group/subgroup1"
projects: ["subgroup2/project1"]

correct path: group/subgroup1/subgroup2
```

#### 4 (No subgroup information)
```
groupName: "group"
projects: ["project1"]

correct path: group
```

In all of the above scenarios, it seems like we can retrieve the group path by combining groupName and project and then popping off the actual project name from the end? (we may need to be careful in scenario 4 that we only write the highest level group once?) @tovbinm @cjwooo What do you all think?

2022-04-12 15:39 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +        yield buildJob(job);
[3b1ec48](https://github.com/faros-ai/airbyte-connectors/pull/367/commits/3b1ec48c3822385a061549bf265708cb7b66f63f)

2022-04-12 15:49 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      yield buildGroup(group);
Thanks. Now I understand what is happening in v1 version. [c021af0](https://github.com/faros-ai/airbyte-connectors/pull/367/commits/c021af048b1651de504fb93eb910bcf10646ba6f) - now I'm retrieving group/sub-group by `groupName` + all sub-groups.

2022-04-12 15:57 UTC, willmarks commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      }
nit: What about the following? since we only really care if a project has subGroup info, we can wait until after checking if the project contains a subgroup to prepend the `builtGroup.fullPath`.
```ts
for (const projectName of projects) {
    // Handle sub-groups in project path Ex: group/subGroup/project
    // https://github.com/faros-ai/feeds/blob/2f7e2745981596b284b54e4d12d99dadba6c06ab/feeds/cicd/gitlabci-feed/src/index.ts#L200
    const projectPathArray = projectName.split('/');
    if (projectPathArray.length > 1) {
        const subGroupPath = projectPathArray.slice(0, -1).join('/');
        if (!subGroupPaths.includes(subGroupPath)) {
            const subGroupPathWithNamespace = `${builtGroup.fullPath}/${subGroupPath}`;
            subGroupPaths.push(subGroupPathWithNamespace);
            const subGroup = await this.client.Groups.show(
                subGroupPath,
                options
            );
            yield buildGroup(subGroup);
        }
    }
}
```

Also what do you think about using a Set for `subGroupPaths` since we are checking containment on line 83.

2022-04-12 17:53 UTC, matussmutny commented on sources/gitlabci-source/src/gitlab/gitlab.ts
> +      }
Thank you, your suggestion makes more sense. Also, I agree about using Set for unique sub-group paths.[f4b98c4](https://github.com/faros-ai/airbyte-connectors/pull/367/commits/f4b98c4635e7c2ca0d0a55dfe9c9c94e1e2d1caa)

2022-04-14 15:28 UTC, cjwooo requested changes
Let's rename to `gitlab-ci-source`.

2022-04-15 13:54 UTC, matussmutny commented
> Let's rename to `gitlab-ci-source`.

[8e2a8cb](https://github.com/faros-ai/airbyte-connectors/pull/367/commits/8e2a8cbae7211bcaf2079f77451fedeabad61802)

2022-04-15 15:53 UTC, cjwooo approved these changes

2022-04-15 15:54 UTC, merged

2022-04-15 20:05 UTC, tovbinm commented
Awesome!!! Thank you @matussmutny @cjwooo @willmarks

2022-04-15 20:06 UTC, tovbinm commented
Please add the new connectors to the README.md