Automatically trigger package & docker container releases on GitHub Release creation
faros-ai/airbyte-connectors pull request #535
Opened 2022-06-16 23:30 UTC by tovbinm

## Description

https://github.com/faros-ai/airbyte-connectors/issues/457

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

2022-06-16 23:42 UTC, cjwooo requested changes
You have to update the cdk dependency version in each of the source and destination package.jsons as well e.g. https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/package.json#L39

2022-06-16 23:44 UTC, tovbinm commented
K, any ideas on how to do it? https://github.com/faros-ai/airbyte-connectors/pull/535#pullrequestreview-1009848780

2022-06-16 23:48 UTC, willmarks commented on scripts/publish-connector.sh
> -connector_version=$(jq -r '.version' < ${connector_path}package.json)
For the cdk version update, can we just manually update it here using jq?

2022-06-17 00:37 UTC, cjwooo approved these changes

2022-06-17 00:38 UTC, merged