Bitbucket Server Source: Part 2
faros-ai/airbyte-connectors pull request #700
Opened 2022-09-22 22:51 UTC by cjwooo

## Description

Add pull_request_activities stream to process PR reviews, comments, and merges.
Add `faros-airbyte-common` internal package for sources and corresponding destination converters to share code (e.g. types, shared data functions)

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-09-22 23:25 UTC, tovbinm commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
what was wrong with this?

2022-09-22 23:30 UTC, cjwooo commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
Lots of converters don't use the StreamContext parameter in the convert() function, which results in lots of eslint-warnings and makes it harder to find and fix other warnings.

2022-09-22 23:33 UTC, tovbinm commented on destinations/airbyte-faros-destination/package.json
> +    "faros-airbyte-common": "0.0.1",
we release [faros-destination as a package on npm](https://www.npmjs.com/package/airbyte-faros-destination), which I presume would also require us to release `faros-airbyte-common`. If this is true, what do we need to modify in the publish flow?

2022-09-22 23:33 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/commits.ts
> +import {Commit} from 'faros-airbyte-common/lib/bitbucket-server/types';
This import seems wrong

2022-09-22 23:33 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/commits.ts
> +    if (!user) return res;
please add a few new lines

2022-09-22 23:34 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/commits.ts
> +    const repoRef = this.vcsRepoRef(project, repo);
can repoRef be null or undefined?

2022-09-22 23:35 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts
> +import {selfHRef, User} from 'faros-airbyte-common/lib/bitbucket-server/types';
same here - the import seems wrong

2022-09-22 23:36 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/project_users.ts
> +    return `${user.project.key};${user.user.slug}`;
perhaps use `:` instead of `;`

2022-09-22 23:37 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts
> +import {selfHRef, User} from 'faros-airbyte-common/lib/bitbucket-server/types';
can we make it `faros-airbyte-common/bitbucket-server` or something?

2022-09-22 23:38 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/pull_request_activities.ts
> +    if (!user) return res;
new lines

2022-09-22 23:39 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/pull_request_activities.ts
> +function reviewState(action: string): {category: string} | undefined {
I think I have seen this function on faros-airbyte-common, no?

2022-09-22 23:40 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/repositories.ts
> +          name: slug,
use repoRef

2022-09-22 23:41 UTC, tovbinm commented on destinations/airbyte-faros-destination/test/converters/bitbucket-server.test.ts
> +describe('bitbucket', () => {
`describe('bitbucket-server'`

2022-09-22 23:41 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/pull_request_activities.ts
> +function reviewState(action: string): {category: string} | undefined {
No

2022-09-22 23:42 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/commits.ts
> +    const repoRef = this.vcsRepoRef(project, repo);
No

2022-09-22 23:42 UTC, tovbinm commented on destinations/airbyte-faros-destination/test/testing-tools.ts
> +    // pino-pretty leaves threads open which can prevent Jest from exiting properly
are the any other report affected by this?

2022-09-22 23:44 UTC, tovbinm commented on sources/bitbucket-server-source/src/streams/common.ts
> +  config: Config;
you gave up of enforcing the config type?

2022-09-22 23:45 UTC, tovbinm commented on sources/bitbucket-server-source/src/streams/pull_requests.ts
> +import {PullRequest} from 'faros-airbyte-common/lib/bitbucket-server/types';
wrong import again.

2022-09-22 23:45 UTC, tovbinm requested changes
see comments

2022-09-22 23:46 UTC, tovbinm commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
I think it's possible to omit the StreamContext argument from the function completely if not used. try it out.

2022-09-22 23:48 UTC, cjwooo commented on sources/bitbucket-server-source/src/streams/common.ts
> +  config: Config;
No I just renamed it. `AirbyteConfig` is the base type.

2022-09-22 23:48 UTC, cjwooo commented on destinations/airbyte-faros-destination/test/testing-tools.ts
> +    // pino-pretty leaves threads open which can prevent Jest from exiting properly
No

2022-09-22 23:49 UTC, tovbinm commented on sources/bitbucket-server-source/src/streams/common.ts
> +  config: Config;
the more explicit type was nicer imho, but ok

2022-09-22 23:49 UTC, cjwooo commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
I did that before and then you said you prefer to list all function parameters.

2022-09-22 23:50 UTC, cjwooo commented on sources/bitbucket-server-source/src/streams/common.ts
> +  config: Config;
It is still the explicit type https://github.com/faros-ai/airbyte-connectors/blob/cwu/bb2/sources/bitbucket-server-source/src/bitbucket-server/index.ts#L20-L29

2022-09-22 23:52 UTC, cjwooo commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
I'd prefer to just remove unused arguments too.

2022-09-22 23:53 UTC, tovbinm commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
ok, you convinced me ;)

2022-09-22 23:54 UTC, tovbinm commented on sources/bitbucket-server-source/src/streams/common.ts
> +  config: Config;
It was better for readability when reviewing the code

2022-09-23 00:40 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts
> +import {selfHRef, User} from 'faros-airbyte-common/lib/bitbucket-server/types';
These imports are valid. We configure our packages to publish code in the `lib` folder. I have not found a way yet to set up the submodule structure you're referring to. The NodeJS module system is complicated enough even before adding Typescript and Lerna requirements into it.

2022-09-23 00:40 UTC, cjwooo commented on destinations/airbyte-faros-destination/package.json
> +    "faros-airbyte-common": "0.0.1",
I updated the flow.

2022-09-23 00:47 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts
> +import {selfHRef, User} from 'faros-airbyte-common/lib/bitbucket-server/types';
How did we fix it for `faros-airbyte-cdk`? Did we re-export everything in `index.ts`? That could work, no?

2022-09-23 00:49 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/bitbucket-server/common.ts
> +import {selfHRef, User} from 'faros-airbyte-common/lib/bitbucket-server/types';
The CDK exports everything at the root level.

2022-09-23 01:03 UTC, cjwooo commented on .eslintrc.js
> +        '@typescript-eslint/no-unused-vars': ['warn', {args: 'none'}],
https://github.com/faros-ai/airbyte-connectors/pull/702

2022-09-23 02:56 UTC, tovbinm approved these changes

2022-09-23 03:03 UTC, merged