Modify the records read from the graph + add converter
faros-ai/airbyte-connectors pull request #797
Opened 2022-11-21 19:41 UTC by ypc-faros

## Description

Introduces a `path_to_record` field to the spec to control how to return the records read from the graph.

Example:

For the query:

```
query MyQuery {
  vcs {
    pullRequests {
      nodes {
        number
      }
    }
  }
}
```

We can return the records as:
```
"vcs": {
      "pullRequests": {
        "nodes": [
                {ORIGINAL_RECORD}
        ]
      }
    }
```
when `path_to_record` is `PATH_TO_MODEL`

or as:
```
"vcs_PullRequest": {ORIGINAL_RECORD}
```
when `path_to_record` is `MODEL_NAME`

The main goal is to be able to control how to output the records in the most appropriate format for piping through a jsonata converter (`PATH_TO_MODEL`) or using the Faros graph converter (`MODEL_NAME`).

## Type of change
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

2022-11-21 19:58 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/faros-graph/faros_graph.ts
> + * This converter is identical to FarosFeed converter.
a nice hack! :)

2022-11-21 20:05 UTC, tovbinm commented on sources/faros-graphql-source/resources/spec.json
> +      "path_to_record": {
how about this instead?
```
"result_model": {
  "order": 6,
  "type": "string",
  "title": "Result model",
  "description": "Where to place each of the query results in their corresponding output records. E.g Nested - { vcs { pullRequests { nodes: [<record>]}}}, Flat - { vcs_PullRequest: <record> }",
  "default": "Nested",
  "enum": [
    "Nested",
    "Flat"
  ]
}
```

2022-11-21 20:11 UTC, tovbinm commented on sources/faros-graphql-source/src/streams/faros-graph.ts
>        this.state = {...this.state, [query]: {refreshedAtMillis}};
This is not very efficient: `this.state = {...this.state, [query]: {refreshedAtMillis}};` avoid the copy `...this.state`

2022-11-21 20:11 UTC, tovbinm commented on sources/faros-graphql-source/src/streams/faros-graph.ts
>        this.state = {...this.state, [query]: {refreshedAtMillis}};
`this.state[query] = {refreshedAtMillis};`

2022-11-21 20:12 UTC, tovbinm commented on sources/faros-graphql-source/src/streams/faros-graph.ts
>        this.state = {...this.state, [query]: {refreshedAtMillis}};
+ perhaps also check for undefined before that

2022-11-21 20:12 UTC, tovbinm requested changes
see comments

2022-11-21 21:39 UTC, ypc-faros commented on sources/faros-graphql-source/resources/spec.json
> +      "path_to_record": {
Done, thanks!

2022-11-21 21:39 UTC, ypc-faros commented on destinations/airbyte-faros-destination/src/converters/faros-graph/faros_graph.ts
> + * This converter is identical to FarosFeed converter.
😉

2022-11-21 21:39 UTC, ypc-faros commented on sources/faros-graphql-source/src/streams/faros-graph.ts
>        this.state = {...this.state, [query]: {refreshedAtMillis}};
Done!

I think `this.state` is guaranteed to be defined. Or did I misunderstand your comment?

2022-11-22 01:43 UTC, tovbinm approved these changes
can you also please add a test where `result_model` is set to `Flat`?

2022-11-22 01:44 UTC, tovbinm commented on sources/faros-graphql-source/src/index.ts
> +
I would just keep the values simple capital case:
```
export enum ResultModel {
  Nested = 'Nested',
  Flat = 'Flat',
}
```

2022-11-22 01:44 UTC, tovbinm approved these changes

2022-11-22 03:35 UTC, merged