Added azure-workitems source and converter
faros-ai/airbyte-connectors pull request #841
Opened 2022-12-20 16:30 UTC by Christopher-Haumann

## Description

> Provide description here

## Type of change
- [ ] New feature

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

Created PullRequest to answer this question https://app.slack.com/client/T033FMD9A73/C0350CRSC3C/thread/C0350CRSC3C-1671186096.781429

2023-01-03 01:36 UTC, tovbinm requested changes

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/resources/schemas/workitem.json
> +
this file should be name `workitems.json`

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/resources/schemas/workitem.json
> +
remove unnecessary newlines at the beginning and the end of the file

2023-01-03 01:36 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/azure-workitems/workitems.ts
> +}
you dont need the main here. simply invoke - https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/bin/main

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/package.json
> +  "description": "Example Airbyte source",
update description

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/package.json
> +  "name": "azure-tasks-source",
update name to `azure-workitems-source`

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/resources/spec.json
> +        "default": "6.0"
update to `7.0`

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +const DEFAULT_API_VERSION = '6.0';
update to `7.0`

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +      timeout: 15000, // default is `0` (no timeout)
make the timeout configurable and update default to `60000`. see https://github.com/faros-ai/airbyte-connectors/blob/main/sources/azure-repos-source/resources/spec.json#L50

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/resources/spec.json
> +      "graph_version": {
remove `graph_version` here and elsewhere since it's not used

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/resources/spec.json
> +      "project": {
`project` argument does not seem to be used - remove from here and elsewhere

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +  private async handleNotFound<T = any, R = AxiosResponse<T>>(
I updated this code to be more robust (same for all other methods). see - https://github.com/faros-ai/airbyte-connectors/blob/main/sources/azure-repos-source/src/azure-repos.ts#L229

2023-01-03 01:36 UTC, tovbinm commented on sources/azure-workitems-source/test/index.test.ts
> +    expect('OK').toEqual('OK');
please add some tests

2023-02-24 15:05 UTC, ypc-faros commented on destinations/airbyte-faros-destination/src/converters/azure-workitems/catalog.json
> +{
Why is this file needed here?

2023-02-24 15:06 UTC, ypc-faros commented on destinations/airbyte-faros-destination/src/converters/azure-workitems/config.json
> +{
Why is this file needed? If it is a test resource, please move

2023-02-24 15:08 UTC, ypc-faros commented on sources/azure-workitems-source/resources/spec.json
> +    "required": ["access_token", "organization", "project"],
You have marked `project` as required, but there's no `project` property. Do we need to add it?

2023-02-24 15:09 UTC, ypc-faros commented on sources/azure-workitems-source/resources/spec.json
> +      "access_token": {
It'd be good to add details about the token requirements (or just a link if you have it)

2023-02-24 15:11 UTC, ypc-faros commented on sources/azure-workitems-source/src/azure-workitems.ts
> +  readonly graph_version?: string;
These should be added to the spec

2023-02-24 15:13 UTC, ypc-faros commented on sources/azure-workitems-source/src/models.ts
> +  //  childOf: string | null
Please remove if not needed

2023-02-24 15:15 UTC, ypc-faros reviewed
Thank you for the contribution! 🥳

2023-02-26 13:45 UTC, Christopher-Haumann commented on sources/azure-workitems-source/resources/spec.json
> +      "access_token": {
It is the same token which is needed in azure-repos-source and azurepipeline-source. In the to sources are also no information about the token requirements in spec.json. I do not have a link ... should I leave a comment there about the requirements?

2023-03-03 16:32 UTC, ypc-faros commented on sources/azure-workitems-source/package.json
> +  "description": "Source to get Azure-Workitems",
Maybe "Azure Workitems Airbyte source"?

2023-03-03 16:37 UTC, ypc-faros commented on sources/azure-workitems-source/src/azure-workitems.ts
> +      timeout: 60000, // default is `0` (no timeout)
You need to use `config.request_timeout` or, if not present, use  60000 as a default (that's what's declared in the spec)

2023-03-06 14:49 UTC, ypc-faros commented on sources/azure-workitems-source/src/azure-workitems.ts
> +      if (ids2.length == 200) {
This seems to imply that there's a max batch size for these kind of requests in the API? Can you extract as a `const` ?

2023-03-06 14:49 UTC, ypc-faros commented on sources/azure-workitems-source/src/azure-workitems.ts
> +      if (ids2.length == 200) {
Same here

2023-03-06 15:03 UTC, ypc-faros commented on sources/azure-workitems-source/resources/schemas/board.json
> +  }
Please add new line at end of file

2023-03-06 15:03 UTC, ypc-faros commented on sources/azure-workitems-source/resources/schemas/iterations.json
> +  }
Please add new line at end of file

2023-03-06 15:03 UTC, ypc-faros commented on sources/azure-workitems-source/resources/spec.json
> +}
Please add new line at end of file

2023-03-06 15:04 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/abnormal_state.json
> +}
newline

2023-03-06 15:04 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/boards.json
> +]
newline

2023-03-06 15:05 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/config.json
> +}
newline

2023-03-06 15:05 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/full_configured_catalog.json
> +}
newline

2023-03-06 15:05 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/incremental_configured_catalog.json
> +}
newline

2023-03-06 15:05 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/iterations.json
> +]
newline

2023-03-06 15:06 UTC, ypc-faros commented on sources/azure-workitems-source/test_files/workitems.json
> +]
newline

2023-03-06 17:01 UTC, Christopher-Haumann commented
I have read the CLA Document and I hereby sign the CLA

2023-03-07 14:15 UTC, ypc-faros commented on destinations/airbyte-faros-destination/src/converters/azure-workitems/common.ts
> +  source = 'AzureWorkitems';
```suggestion
  source = 'Azure-Workitems';
```

2023-03-07 17:27 UTC, ypc-faros approved these changes
Thank you @Christopher-Haumann for your contribution!!! 🥳

2023-03-07 18:48 UTC, tovbinm commented on sources/azure-workitems-source/package.json
> +    ],
please remove `testPathIgnorePatterns` section

2023-03-07 18:50 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
Use `Promise.all(...)` instead https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2023-03-07 21:59 UTC, tovbinm approved these changes
@Christopher-Haumann see comments. otherwise lgtm!

can you also please update https://github.com/faros-ai/airbyte-connectors/blob/main/README.md ?

2023-03-07 21:59 UTC, tovbinm commented
Thank you for the contribution @Christopher-Haumann !!!

2023-03-08 16:47 UTC, Christopher-Haumann commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
How exactly should I use Promise.all() in this  case?

2023-03-08 19:25 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
```typescript
ids.push(...await Promise.all(
  await this.getIdsFromAWorkItemType("'Task'"),
  await this.getIdsFromAWorkItemType("'User Story'"),
  await this.getIdsFromAWorkItemType("'BUG'"),
  await this.getIdsFromAWorkItemType("'Feature'"),
  await this.getIdsFromAWorkItemType("'Epic'"),
  await this.getIdsFromAWorkItemType("'Issue'"),
  await this.getIdsFromAWorkItemType("'Product Backlog Item'"),
  await this.getIdsFromAWorkItemType("'Requirement'")
));
```

2023-03-08 19:26 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
Or better:
```typescript
const getIds = [
  "'Task'",
  "'User Story'",
  "'BUG'",
  "'Feature'",
  "'Epic'",
  "'Issue'",
  "'Product Backlog Item'",
  "'Requirement'"
].map((name) => await this.getIdsFromAWorkItemType(name));

ids.push(...await Promise.all(getIds));
```

2023-03-08 21:53 UTC, Christopher-Haumann commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
With the first solution I get "Expected 1 arguments, but got 8." with the second solution I get "Argument of type 'string[]' is not assignable to parameter of type 'string'"

2023-03-09 00:07 UTC, willmarks commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
For the first example, Promise.all takes an array of Promises so you would want to remove all of the `awaits` and wrap all of the various calls to `getIdsFromAWorkItemType` in an array.

For the second example, that seems like that should have worked. Does the error have a stacktrace that shows you what is expecting a `string` but is getting a `string[]`? If it is where the `Promise.all(getIds)` is being spread into the `ids.push()`, then maybe you need to switch that line to the following to make sure you await before spreading?
```ts
ids.push(...(await Promise.all(getIds))); 
```

2023-03-09 17:09 UTC, merged

2023-03-09 17:23 UTC, tovbinm commented on sources/azure-workitems-source/src/azure-workitems.ts
> +    ids.push(...(await this.getIdsFromAWorkItemType("'Requirement'")));
FYI - https://github.com/faros-ai/airbyte-connectors/pull/953