Process nested group repo keys correctly
faros-ai/airbyte-connectors pull request #892
Opened 2023-01-26 23:04 UTC by BrentSouza

## Description

GitLab supports nested groups which need to be considered when parsing the repo key. For example,

`top-level-group / nested-group / project`

Currently, `nested-group` is being treated as the project name and uid. This patch changes the parsing so that:

name = project
uid = nested-group / project

## Type of change
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#891]()

2023-01-26 23:15 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    const repositoryName = orgRepo.slice(repositoryIndex, orgRepo.length).join(' / ');
```suggestion
const repositoryUid = orgRepo.slice(repositoryIndex, orgRepo.length).join('/').toLowerCase();
const repositoryName = orgRepo[orgRepo.length - 1].toLowerCase();
return {
      name: repositoryName,
      uid: repositoryUid,
      organization: {uid: organization?.toLowerCase(), source},
};
```

2023-01-26 23:16 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
generally with `startIndex = 3` hardcoded above, we should just rewrite this function (cc @thomas-gerber / @cjwooo )

2023-01-27 19:23 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    const repositoryName = orgRepo.slice(repositoryIndex, orgRepo.length).join(' / ');
Yeah. I was considering this same change to be honest. Do you know if there is any particular reason `toLowerCase()` is called on everything?

2023-01-27 21:52 UTC, BrentSouza commented
I have read the CLA Document and I hereby sign the CLA

2023-01-30 18:03 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
Let's remove that index parameter and instead parse the webUrl with https://nodejs.org/docs/latest-v16.x/api/url.html#new-urlinput-base

2023-01-30 18:09 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
I have 0 attachment to this code as I didn't create it, but what does parsing the URL get you in this case? The logic is really in parsing the pathname, which still requires some knowledge of where to start looking for the relevant tokens.

2023-01-30 18:26 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
Code readability + eliminate error chance of someone calling this function with an invalid index.

2023-01-30 18:29 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
Oh I just saw that this function is called in one place with a different startIndex so we can't remove that parameter.

2023-01-30 18:32 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
Just to provide a little more context about what is going on with this function...

I believe the reason the original author of this converter added the startIndex parameter is that one of the streams (group milestones) returns a slightly different pattern for the webUrl. GitLab prefixes this with the word "groups". You can see this in the patterns below:

| stream | web_url |
| ------ | ------- |
| branches | https://gitlab.com/org/repo/-/tree/main |
| commits | https://gitlab.com/org/repo/-/commit/ed899a2f4b50b4370feeea94676502b42383c746 |
| group_milestones | https://gitlab.com/groups/org/-/milestones/42 |
| jobs | https://gitlab.com/org/repo/-/jobs/7 |
| merge_request_commits | https://gitlab.com/org/repo/-/merge_requests/133 |
| merge_requests | http://gitlab.com/org/repo/-/merge_requests/1 |
| pipelines | https://gitlab.com/org/repo/-/pipelines/47 |
| project_milestones | https://gitlab.com/org/repo/-/milestones/1 |
| projects | https://gitlab.com/org/repo |
| tags | https://gitlab.com/org/repo/-/commit/ed899a2f4b50b4370feeea94676502b42383c746 |

So the intent of `startIndex` is just to know where in the path to extract `org`. So I think creating a URL object from `webUrl` in this case doesn't help really. We would end up doing something like:

```ts
static parseRepositoryKey(webUrl, source, hasGroupPrefix = false) {
    const parsedUrl = new URL(webUrl);
    const nameParts = parsedUrl.pathName.split('/');
    const startIndex = hasGroupPrefix ? 1 : 0;
    //  rest of the logic is the same 
   ...
}
```

2023-01-30 18:34 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
Which I'm happy to do if that's what you prefer. I just don't see value in creating a URL object.

Actually I think this function needs some more work regardless to handle that `group_milestones` special case

2023-01-30 18:43 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
Is group_milestones the only special case? It seems like we are not converting those records properly, given that we are currently trying to parse a repository from what seems like a group-level item. @tovbinm @thomas-gerber

2023-01-30 19:43 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
It is, but I am really looking deeper now and I think the way group milestones are being handled in general is not correct. Both project and group milestones are being converted to `tms_Epic`. Projects, are loaded to `tms_Project`, however groups are not, so the linkage for `tms_Epic` to `tms_Project` will be missing/incorrect for group milestones.

I think I'll have to modify the converter for `Groups` to also make an entry in `tms_Project`. Since group ids and project ids in GitLab are independent, the issue then is avoiding collision with the ids, but I think that can be managed if we do something like prefix the group id with a `g`.

With that in place, I think we can change group milestones to ignore parsing `web_url` since the `group_id` is a property in the response object.

That would allow us to remove the `streamIndex` parameter.

2023-01-30 20:55 UTC, cjwooo commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
I haven't really worked with GitLab myself. @thomas-gerber wdyt^? specifically regarding the proposed converter change.

2023-01-31 05:37 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    if (orgRepo.length <= repositoryIndex) return undefined;
I ended up doing something slightly different which I think addresses all of the issues. 

* **Preventing improper use of parseRepositoryKey**: There are now two separate functions for handling the different url patterns, with a private function to handle the common parsing logic. 
* **Prevent key overlap in tms_Project**: Groups and Projects will now register with the same uid as vcs_Repository/vcs_Organization, which are full paths and can't overlap.
* **Incorrect data model**: I went through all of the stream converters and made sure they are using values that will prevent clobbering and improper associations to repos/groups

I think this set of changes is pretty close to modeling the data according to what I can see in my GitLab instance. One thing that's missing still is support for GitLab's epics.

Additionally, I opened airbytehq/airbyte#22124 in the airbyte project to address some data erasure from the source. If that gets fixed, it could simplify some of the stream dependencies present in the converters.

2023-01-31 22:36 UTC, thomas-gerber requested changes
Summary of the changes requested (open to discussion), assuming `top-level-group / nested-group / project`:
1. vcs_Organization and cicd_Organization should have exactly one entry: `top-level-group`
2. tms_Project should have one entry: `nested-group / project`; the schema is missing a tms_Organization entity, when we add it later it will not break any user if we are consistent this way
3. vcs_Repository should have one entry: `nested-group / project`
4. tms_Board should have 2 entries: `project` and `nested-group / project`; as well as the corresponding 2 tms_TaskBoardProjectRelationship entries between the one project and 2 boards
4. an issue in that project should belong to those 2 tms_TaskBoards (through tms_TaskBoardRelationship) and that one tms_Project (through tms_TaskProjectRelationship)

This will ensure that existing users without subgroup are unchanged.
The limitation that I see is that the UID for tms_Project and tms_TaskBoard is not unique (because `top-level-group` is not part of it), but that can be solved later with a tms_Organization entity.

2023-01-31 22:36 UTC, thomas-gerber commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    const uid = nameParts.slice(startIndex, endIndex).join('/').toLowerCase();
in order not to break existing users who do not use subgroups, I think uid should NOT include the top level folder (i.e. slice with `startIndex + 1`).
for `top-level-group / nested-group / project`, uid is `nested-group / project`; the org is what has the top level.

2023-01-31 22:36 UTC, thomas-gerber commented on destinations/airbyte-faros-destination/src/converters/gitlab/groups.ts
> +        uid: group.full_path,
I think we should only create ONE entry for cicd_Organization and ONE entry for vcs_Organization based on the `top-level-group`.
We also create one tms_TaskBoard per Gitlab group (`uid` comment above applies)
Then, in the project stream, we create ONE tms_Project by Project, link it to all boards from its hierarchy,

2023-01-31 22:36 UTC, thomas-gerber commented on destinations/airbyte-faros-destination/src/converters/gitlab/issues.ts
> +    res.push(
see comments above on relationships; I think an issue (tms_Task) should link to a single tms_Project, but could link to several tms_TaskBoards.

2023-02-01 01:00 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/issues.ts
> +    res.push(
I agree. This makes more sense as issues are a Project level item.

2023-02-01 01:06 UTC, BrentSouza commented on destinations/airbyte-faros-destination/src/converters/gitlab/common.ts
> +    const uid = nameParts.slice(startIndex, endIndex).join('/').toLowerCase();
> The limitation that I see is that the UID for tms_Project and tms_TaskBoard is not unique (because top-level-group is not part of it), but that can be solved later with a tms_Organization entity.

Thanks for the feedback. In addition I think `tms_Epic` and `tms_TaskProjectRelationship` would have the same issue and this limitation that you mention is why I included the `top-level-group` in the `uid`. I felt that if I was making a PR to address broken relationships in the data model that I should be complete with it. However, I agree that if there are plans to create a `tms_Organization` entity, that would be a better path. I'll change this back to exclude the `top-level-group`

2023-02-01 19:58 UTC, BrentSouza commented
@thomas-gerber I think `cicd_Release` also needs some attention.

With the changes to `vcs_Repository.uid` to include nested groups, which will then flow `vcs_Tags`, we should be able to link everything correctly. However, `cicd_Release.uid` only has the release name which is not unique, so that would cause inaccuracies with descriptions, dates, and urls across projects that have the same release name, which is fairly common if using semver release names.

Should `cicd_Release` also be aware of Org and include `nested-group/project` in the uid?

2023-02-01 21:25 UTC, BrentSouza commented
Latest commits should address the changes requested 😃

2023-02-02 00:28 UTC, thomas-gerber commented
> @thomas-gerber I think `cicd_Release` also needs some attention.
> 
> With the changes to `vcs_Repository.uid` to include nested groups, which will then flow `vcs_Tags`, we should be able to link everything correctly. However, `cicd_Release.uid` only has the release name which is not unique, so that would cause inaccuracies with descriptions, dates, and urls across projects that have the same release name, which is fairly common if using semver release names.
> 
> Should `cicd_Release` also be aware of Org and include `nested-group/project` in the uid?

Both your points on linkage working and UID not being unique are valid. **I agree that the uid should be `nested-group/project/releasename` (notice the absence of top-level-group).** Later, we may link to a cicd_Organization, although this already links to vcs_Organization through the tag.

2023-02-02 00:40 UTC, thomas-gerber requested changes
One small fix needed:
given `top-level-group/nested-group1/nested-group2/project`, you create the following boards:
* top-level-group
* nested-group1
* nested-group1/nested-group2
* nested-group1/nested-group2/project
The first one (top-level-group) should not be there IMO.
(Same remark for tms_TaskBoardRelationship and tms_TaskBoardProjectRelationship)

Otherwise, I agreed with your comment on cicd_Release, and you can update the UID as you suggested (i.e. append `nested-group/project`) even though it may break backward compatibility.

I checked the rest of entities on my test instances with a nested group, and it looks good. I also sanity checked the other converters, and I haven't found any other places to update, great job!

2023-02-02 00:48 UTC, thomas-gerber commented
> One small fix needed: given `top-level-group/nested-group1/nested-group2/project`, you create the following boards:
> 
> * top-level-group
> * nested-group1
> * nested-group1/nested-group2
> * nested-group1/nested-group2/project
>   The first one (top-level-group) should not be there IMO.
>   (Same remark for tms_TaskBoardRelationship and tms_TaskBoardProjectRelationship)
> 
> Otherwise, I agreed with your comment on cicd_Release, and you can update the UID as you suggested (i.e. append `nested-group/project`) even though it may break backward compatibility.
> 
> I checked the rest of entities on my test instances with a nested group, and it looks good. I also sanity checked the other converters, and I haven't found any other places to update, great job!

Unless you have a specific use case in mind that I didn't grasp?

2023-02-02 01:12 UTC, BrentSouza commented
My thinking was just keeping inline with what you can see in GitLab. If I navigate to a top-level-group in my instance, I can see all issues for child projects no matter where they sit in a nested group hierarchy. So I think a board to represent that top-level-group is a natural expectation for a GitLab user, but I think you could very easily create a query to get all Tasks in a given top-level-group when tms_Organization is created and linked to tms_TaskProjectRelationship.

I'll remove that and update the uid for cicd_Release.

Side note...Is there anything I can do about the errant CLA user? I goofed with my first commit using my default git profile for work so it didn't link the commit to my GitHub user account correctly.

2023-02-02 06:08 UTC, thomas-gerber approved these changes
Thank you @BrentSouza , this was an impressive contribution that went deep into the nuance of the data model!

2023-02-02 06:21 UTC, thomas-gerber commented
Bypassing the CLA assistant as the 2 committers are the same person.

2023-02-02 06:21 UTC, merged

2023-02-02 07:03 UTC, thomas-gerber commented
@BrentSouza released `v0.4.67` https://github.com/faros-ai/airbyte-connectors/releases/tag/v0.4.67

2023-02-02 16:48 UTC, tovbinm commented
Thank you for all the great work!! @BrentSouza