FAI-1849 - Octopus connector
faros-ai/airbyte-connectors pull request #954
Opened 2023-03-09 23:27 UTC by willmarks

## Description

Adds an Octopus connector with a deployment and release stream.

## Type of change
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change

2023-03-10 19:59 UTC, tovbinm requested changes
Any

2023-03-10 19:59 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/octopus/deployments.ts
> +    const status = octopusStatus?.toLowerCase();
since you are lowercasing the value here, all the cases below should be lowercased as well.

2023-03-10 19:59 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/octopus/deployments.ts
> +        return {category: 'Prod', detail: env};
I would do `const detail = octopusEnv` as is.

2023-03-10 19:59 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/octopus/releases.ts
> +      record: {
no other info we can fill in here?

2023-03-10 19:59 UTC, tovbinm commented on destinations/airbyte-faros-destination/test/converters/octopus.test.ts
> +    const processedByStream = {
it would be nice to have a little bit more data that just 4 records.

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/bin/main
> +#!/usr/bin/env node
make sure to do `chmod +x` on this file

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/package.json
> +    "@octopusdeploy/api-client": "^3.0.6",
do we need `@octopusdeploy/api-client`? perhaps we can just use axios

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/resources/spec.json
> +        "title": "Octopus Api Key",
Api -> API

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/resources/spec.json
> +        "title": "Octopus Spaces to Sync.",
1. `Octopus Spaces to Sync.` -> `Octopus Spaces to Sync`
2. If none provided, can we sync all of them? (same as we do in other sources)

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/resources/spec.json
> +        "title": "Page Size"
default value?

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/models.ts
> +        nonOctopusProp(key)
why is this cleaning needed?

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +      throw new VError('api key must be provided');
api key -> API Key

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +      throw new VError('instance url must be provided');
instance url -> `Instance URL`

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +      throw new VError('No spaces could be resolved.');
why is this an error? we should be able to move on, it would not produce any records. We can just write a warn about it.

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +      throw new VError('No spaces could be resolved.');
since you are assuming an error in `checkConnection()`, then you make the above behavior modifiable through an argument

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +        );
I think you can do `Promise.all` here to fire all there calls in parallel.

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +      for await (const deployment of this.client.listDeployments(spaceId)) {
additionally you could also batch deployments into chunks and fetch several in parallel

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +    for (const [spaceId, spaceName] of Object.entries(this.spaces)) {
same - additionally you could also batch releases into chunks and fetch several in parallel

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/resources/spec.json
> +}
we should offer a cutoff of days (e.g 90) to limit the amount of data we fetch

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopusClient.ts
> +const DEFAULT_PAGE_SIZE = 1;
what?! page size of 1?!

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/octopusClient.ts
> +const DEFAULT_MAX_RETRIES = 3;
num of retries should be configurable through spec

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/streams/deployments.ts
> +    const octopus = await Octopus.instance(this.config, this.logger);
why cant we create a `Octopus.instance` once and pass it into each stream instead of initializing it in each stream?

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/test_files/config.json
> +  "api_key": "key",
"key" -> "dummy-key" and "url" -> "dummy-url" so it would be easier to troubleshoot

2023-03-10 19:59 UTC, tovbinm commented on sources/octopus-source/src/streams/deployments.ts
> +export class Deployments extends AirbyteStreamBase {
are the any plans to support incremental sync for these two streams?

2023-03-10 22:12 UTC, willmarks commented on destinations/airbyte-faros-destination/test/converters/octopus.test.ts
> +    const processedByStream = {
Sounds good, Ill add some more things.

2023-03-10 22:12 UTC, willmarks commented on sources/octopus-source/package.json
> +    "@octopusdeploy/api-client": "^3.0.6",
I kept the client around for all of the models that they offer. I am using axios for all of the API calls.

2023-03-10 22:12 UTC, willmarks commented on sources/octopus-source/resources/spec.json
> +        "title": "Octopus Spaces to Sync.",
2. Yes, currently if none are provided I sync all.

2023-03-10 22:12 UTC, willmarks commented on sources/octopus-source/src/models.ts
> +        nonOctopusProp(key)
Its a ton of useless stuff otherwise.

2023-03-10 22:21 UTC, willmarks commented on sources/octopus-source/src/streams/deployments.ts
> +    const octopus = await Octopus.instance(this.config, this.logger);
Its a singleton so its only initialized once. I can see about passing it in.

2023-03-11 00:08 UTC, tovbinm commented on sources/octopus-source/package.json
> +    "@octopusdeploy/api-client": "^3.0.6",
Let's copy over the models.

2023-03-11 00:09 UTC, tovbinm commented on sources/octopus-source/src/models.ts
> +        nonOctopusProp(key)
Can you share an example? We don't typically do this in our sources.

2023-03-11 00:10 UTC, tovbinm commented on sources/octopus-source/src/streams/deployments.ts
> +    const octopus = await Octopus.instance(this.config, this.logger);
Great. No action needed then.

2023-03-14 16:58 UTC, willmarks commented on sources/octopus-source/src/octopus.ts
> +      for await (const deployment of this.client.listDeployments(spaceId)) {
I like the idea. I think I'll leave it as it for now and maybe we can add that improvement in the future.

2023-03-14 16:58 UTC, willmarks commented on sources/octopus-source/src/octopus.ts
> +    for (const [spaceId, spaceName] of Object.entries(this.spaces)) {
same as above.

2023-03-14 16:58 UTC, willmarks commented on sources/octopus-source/src/models.ts
> +        nonOctopusProp(key)
Just commenting for other's context: we discussed this and because this is an additional piece of information that I am adding to each deployment, cleaning it is fine.

2023-03-14 18:26 UTC, ypc-faros commented on sources/octopus-source/src/octopus.ts
> +   * If no spaceNames are provided, all spaces will be included.
Lets include this in the corresponding field description (If no spaceNames are provided, all spaces will be included.)

2023-03-14 18:29 UTC, ypc-faros commented on sources/octopus-source/src/octopus.ts
> +    private readonly lookBackDepth = 0
Shouldn't this default to 10? (as per the spec)

2023-03-14 18:44 UTC, ypc-faros commented on sources/octopus-source/resources/spec.json
> +    "properties": {
Can we add descriptions for the fields that are not self-explanatory?

cutoff_days
look_back_depth

2023-03-14 18:46 UTC, ypc-faros approved these changes

2023-03-14 18:47 UTC, ypc-faros approved these changes

2023-03-14 19:23 UTC, tovbinm approved these changes
see comments

2023-03-14 19:23 UTC, tovbinm commented on destinations/airbyte-faros-destination/src/converters/octopus/deployments.ts
> +          name: deployment._extra?.ProjectName,
on the second thought, I am not a big fan on `_extra` property. Let's remove it.

2023-03-14 19:23 UTC, tovbinm commented on destinations/airbyte-faros-destination/test/converters/octopus.test.ts
> +    const processedByStream = {
6 entries! ;)

2023-03-14 19:23 UTC, tovbinm commented on sources/octopus-source/src/octopusClient.ts
> +    this.api = axios.create({
let's also increase the response timeout; and set max response body size to infinity

2023-03-14 19:23 UTC, tovbinm commented on sources/octopus-source/src/streams/deployments.ts
> +    const currentIdNum = lastId ? +lastId.match(this.idNumRegex)[1] : 0;
can we potentially get Array out of bound exception with `[1]` access?

2023-03-14 19:23 UTC, tovbinm commented on sources/octopus-source/resources/spec.json
> +        "default": 10
is this a good enough default?

2023-03-14 19:23 UTC, tovbinm commented on sources/octopus-source/src/octopus.ts
> +        if (this.cutoff && DateTime.fromISO(release.Assembled) < this.cutoff) {
`release.Assembled` is created at? or?

2023-03-14 19:32 UTC, willmarks commented on sources/octopus-source/src/octopus.ts
> +        if (this.cutoff && DateTime.fromISO(release.Assembled) < this.cutoff) {
Yeah it is.

2023-03-14 19:42 UTC, willmarks commented on sources/octopus-source/resources/spec.json
> +        "default": 10
Im not totally sure cause it depends on how many deployments are being produced per unit of time. I think 10 is a good starting place though and we can adjust as needed.

2023-03-14 19:43 UTC, willmarks commented on sources/octopus-source/src/streams/deployments.ts
> +    const currentIdNum = lastId ? +lastId.match(this.idNumRegex)[1] : 0;
It should just be undefined which is handled.

2023-03-14 20:52 UTC, merged

2023-03-14 22:11 UTC, tovbinm commented on sources/octopus-source/src/octopusClient.ts
> +      baseURL: `${config.instanceUrl}/api`,
@willmarks  Strip suffix `/` if present in `config.instanceUrl`